/*
 * Copyright (c) 2025 LoxiLB Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at:
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * ai_kv_jinja.go — Jinja template executor for profile-pinned chat
 * templates.
 *
 * The KV-exact chat surface must render byte-identically to the engine's
 * apply_chat_template. Engines render with HF transformers' Jinja environment
 * (ImmutableSandboxedEnvironment, trim_blocks=True, lstrip_blocks=True,
 * keep_trailing_newline=False, the loopcontrols extension, a json.dumps-based
 * tojson, raise_exception and strftime_now globals), so this executor
 * implements those exact whitespace semantics plus the language the pinned
 * production templates use:
 *
 *   statements  if/elif/else, for (tuple targets, inline if-filter, else,
 *               loop.* incl. previtem/nextitem), set (name, namespace
 *               attribute, tuple, block set), macro + call, continue, break
 *   expressions literals (str with Python escapes, int, bool, none, list,
 *               tuple, dict), conditional a if c else b, and/or/not,
 *               comparisons, in / not in, + - * // % ~, attribute,
 *               subscript and slice, calls with keyword arguments,
 *               filters and tests with arguments
 *
 * Filters, tests, methods and globals live in ai_kv_jinja_builtin.go; the
 * value model and the Python text conversions in ai_kv_jinja_value.go.
 *
 * Anything outside the subset fails loudly: unknown constructs are compile
 * errors, unknown filters/tests/methods and type mismatches are render
 * errors. A render error on a strict rule surfaces as a runtime fault (the
 * caller's contract), never as silently different bytes. Parity is proven
 * two ways: per construct against the rows of
 * cicd/common/kv_hash/fixtures/kv_jinja_construct_parity.json, and per model
 * against the whole-template goldens of kv_chat_render_parity.json — both
 * generated by the HF renderer itself, never by this executor.
 */

package loxinet

import (
	"errors"
	"fmt"
	"strconv"
	"strings"
	"unicode"
)

// kvJjUndef is the Jinja Undefined value: falsy, renders as "", equals
// only another Undefined, iterates as empty, and raises on stricter use
// (attribute/subscript access, +, ordering, method calls).
type kvJjUndef struct{ name string }

// kvJjNS is a namespace() object: the one mutable-by-reference value in the
// subset (Jinja for-loop scopes are per-iteration, so templates thread
// cross-iteration state through namespace attributes).
type kvJjNS struct{ attrs map[string]any }

// kvJjBound is a Python bound method reached as a value (d.items without a
// call). It is callable and truthy; printing it is refused.
type kvJjBound struct {
	obj  any
	name string
}

// kvJinjaTemplate is a compiled template. Compilation is pure; Render may be
// called concurrently.
type kvJinjaTemplate struct {
	nodes []kvJjNode
	// names is every variable name the template reads — the render context
	// it can observe (e.g. whether it consults strftime_now).
	names map[string]bool
	// iteratesContent: some for loop iterates a content value (see
	// kvJjIsContentAccess).
	iteratesContent bool
}

// References reports whether the template reads the named variable.
func (t *kvJinjaTemplate) References(name string) bool { return t.names[name] }

// IteratesContent reports a for loop over x.content, x['content'] or a
// variable named content, through filters, tests and slices, on any base.
// vLLM v0.28.0 (renderers/hf.py _detect_content_format) and SGLang v0.5.18
// (detect_jinja_template_content_format) switch a template to the "openai"
// content format on a subset of these loops — they require the base to be
// a message loop variable — so this is a superset of both.
func (t *kvJinjaTemplate) IteratesContent() bool { return t.iteratesContent }

type kvJjError struct {
	pos int
	msg string
}

func (e *kvJjError) Error() string {
	return fmt.Sprintf("jinja: offset %d: %s", e.pos, e.msg)
}

func kvJjErrf(pos int, format string, a ...any) error {
	return &kvJjError{pos: pos, msg: fmt.Sprintf(format, a...)}
}

// kvJjAt positions a builtin's error at the expression that raised it.
func kvJjAt(pos int, err error) error {
	if err == nil {
		return nil
	}
	var je *kvJjError
	var re *kvJjRaised
	if errors.As(err, &je) || errors.As(err, &re) || errors.Is(err, kvJjBreakSig) || errors.Is(err, kvJjContinueSig) {
		return err
	}
	return &kvJjError{pos: pos, msg: err.Error()}
}

// ---------------------------------------------------------------------------
// Segment lexer: split source into text and {% %} / {{ }} / {# #} tags, then
// apply the whitespace-control rules the engine environment uses.

type kvJjSegKind int

const (
	kvJjSegText kvJjSegKind = iota
	kvJjSegBlock
	kvJjSegOutput
	kvJjSegComment
)

type kvJjSeg struct {
	kind      kvJjSegKind
	body      string // tag interior (trim markers removed) or raw text
	pos       int
	trimLeft  bool
	trimRight bool
	noLstrip  bool // {%+ disables lstrip_blocks for this tag
}

func kvJjLex(src string) ([]kvJjSeg, error) {
	// keep_trailing_newline=False: exactly one trailing newline is dropped
	// before any other processing.
	src = strings.TrimSuffix(src, "\n")

	var segs []kvJjSeg
	i := 0
	for i < len(src) {
		open := strings.IndexByte(src[i:], '{')
		for open >= 0 {
			j := i + open
			if j+1 < len(src) && (src[j+1] == '%' || src[j+1] == '{' || src[j+1] == '#') {
				break
			}
			open = strings.IndexByte(src[i+open+1:], '{')
			if open >= 0 {
				open += j - i + 1
			}
		}
		if open < 0 {
			segs = append(segs, kvJjSeg{kind: kvJjSegText, body: src[i:], pos: i})
			break
		}
		start := i + open
		if start > i {
			segs = append(segs, kvJjSeg{kind: kvJjSegText, body: src[i:start], pos: i})
		}
		var kind kvJjSegKind
		var closer string
		switch src[start+1] {
		case '%':
			kind, closer = kvJjSegBlock, "%}"
		case '{':
			kind, closer = kvJjSegOutput, "}}"
		case '#':
			kind, closer = kvJjSegComment, "#}"
		}
		end, err := kvJjFindClose(src, start+2, closer, kind != kvJjSegComment)
		if err != nil {
			return nil, err
		}
		body := src[start+2 : end]
		seg := kvJjSeg{kind: kind, pos: start}
		if strings.HasPrefix(body, "-") {
			seg.trimLeft = true
			body = body[1:]
		} else if kind == kvJjSegBlock && strings.HasPrefix(body, "+") {
			seg.noLstrip = true
			body = body[1:]
		}
		if strings.HasSuffix(body, "-") {
			seg.trimRight = true
			body = body[:len(body)-1]
		}
		seg.body = strings.TrimSpace(body)
		segs = append(segs, seg)
		i = end + 2
	}

	// Whitespace control, in the engine environment's order: explicit -
	// markers strip all adjacent whitespace; otherwise lstrip_blocks removes
	// a line-leading indent before a block/comment tag and trim_blocks
	// removes the single newline after one. Output tags get neither default.
	for k := range segs {
		if segs[k].kind != kvJjSegText {
			continue
		}
		// Whether the trailing blank run starts a line is a property of the
		// source text, decided before trim_blocks eats the newline that
		// precedes it.
		orig := segs[k].body
		run := len(orig)
		for run > 0 && (orig[run-1] == ' ' || orig[run-1] == '\t') {
			run--
		}
		runAtLineStart := run < len(orig) && (run == 0 && segs[k].pos == 0 || run > 0 && orig[run-1] == '\n')
		if k > 0 {
			prev := &segs[k-1]
			if prev.trimRight {
				segs[k].body = strings.TrimLeft(segs[k].body, " \t\r\n")
			} else if prev.kind == kvJjSegBlock || prev.kind == kvJjSegComment {
				segs[k].body = strings.TrimPrefix(segs[k].body, "\n")
			}
		}
		if k+1 < len(segs) {
			next := &segs[k+1]
			if next.trimLeft {
				segs[k].body = strings.TrimRight(segs[k].body, " \t\r\n")
			} else if (next.kind == kvJjSegBlock || next.kind == kvJjSegComment) && !next.noLstrip && runAtLineStart {
				// Strip only a run that starts at a line start (or template
				// start) — mid-line whitespace before a tag is content. The
				// left-side trims above never reach into a run that has a
				// newline before it; a run that was the whole segment is
				// already gone or is removed here.
				t := segs[k].body
				segs[k].body = strings.TrimRight(t, " \t")
			}
		}
	}
	return segs, nil
}

// kvJjFindClose finds the tag closer. Inside {% %} and {{ }} quoted strings
// are skipped (template string literals may contain braces and newlines);
// comment text is opaque, so apostrophes there are plain characters.
func kvJjFindClose(src string, from int, closer string, skipStrings bool) (int, error) {
	for i := from; i < len(src)-1; i++ {
		c := src[i]
		if skipStrings && (c == '\'' || c == '"') {
			q := c
			i++
			for i < len(src) {
				if src[i] == '\\' {
					i += 2
					continue
				}
				if src[i] == q {
					break
				}
				i++
			}
			if i >= len(src) {
				return 0, kvJjErrf(from, "unterminated string literal")
			}
			continue
		}
		if c == closer[0] && src[i+1] == closer[1] {
			// A '-' right-trim marker sits between body and closer.
			return i, nil
		}
	}
	return 0, kvJjErrf(from, "unterminated tag (missing %s)", closer)
}

// ---------------------------------------------------------------------------
// Statement nodes.

type kvJjNode interface {
	exec(rt *kvJjRT, sb *strings.Builder) error
}

type kvJjText struct{ s string }

type kvJjOutput struct {
	e   kvJjExpr
	pos int
}

type kvJjIf struct {
	conds  []kvJjExpr // one per if/elif branch
	bodies [][]kvJjNode
	els    []kvJjNode
}

type kvJjFor struct {
	targets []string // one name, or a tuple unpack
	seq     kvJjExpr
	filter  kvJjExpr // inline `if` filter, nil when absent
	body    []kvJjNode
	els     []kvJjNode
	pos     int
}

type kvJjSet struct {
	targets []string // one name, or a tuple unpack
	attr    string   // namespace attribute assignment (single target)
	e       kvJjExpr
	pos     int
}

type kvJjSetBlock struct {
	name string
	body []kvJjNode
}

type kvJjMacroDecl struct {
	name     string
	params   []string
	defaults []kvJjExpr // parallel to params; nil = no default
	body     []kvJjNode
	pos      int
}

// kvJjMacro is a defined macro: calling it renders its body to a string.
type kvJjMacro struct{ decl *kvJjMacroDecl }

type kvJjMacroDef struct{ decl *kvJjMacroDecl }

type kvJjLoopCtl struct{ brk bool }

var (
	kvJjBreakSig    = errors.New("jinja: break")
	kvJjContinueSig = errors.New("jinja: continue")
)

// kvJinjaCompile parses template source into an executable node tree.
func kvJinjaCompile(src string) (*kvJinjaTemplate, error) {
	segs, err := kvJjLex(src)
	if err != nil {
		return nil, err
	}
	p := &kvJjSegParser{segs: segs, names: map[string]bool{}}
	nodes, err := p.parseBody(nil)
	if err != nil {
		return nil, err
	}
	// varargs/kwargs/caller are implicit macro locals the executor does not
	// model; a template reading them must refuse rather than see Undefined.
	for _, n := range []string{"varargs", "kwargs", "caller"} {
		if p.names[n] {
			return nil, kvJjErrf(0, "unsupported implicit macro variable %q", n)
		}
	}
	return &kvJinjaTemplate{nodes: nodes, names: p.names, iteratesContent: p.iteratesContent}, nil
}

type kvJjSegParser struct {
	segs            []kvJjSeg
	i               int
	loopDepth       int
	names           map[string]bool
	iteratesContent bool
}

// kvJjIsContentAccess reports an expression that reads a content value:
// x.content, x['content'] or the variable content, under any filters,
// tests and slices.
func kvJjIsContentAccess(e kvJjExpr) bool {
	for {
		switch x := e.(type) {
		case *kvJjFilter:
			e = x.e
		case *kvJjTest:
			e = x.e
		case *kvJjSlice:
			e = x.obj
		case *kvJjAttr:
			return x.name == "content"
		case *kvJjIndex:
			lit, ok := x.idx.(*kvJjLit)
			return ok && lit.v == "content"
		case *kvJjVar:
			return x.name == "content"
		default:
			return false
		}
	}
}

// parseBody parses statements until one of the terminator keywords appears,
// which is left un-consumed for the caller.
func (p *kvJjSegParser) parseBody(until []string) ([]kvJjNode, error) {
	var nodes []kvJjNode
	for p.i < len(p.segs) {
		seg := p.segs[p.i]
		switch seg.kind {
		case kvJjSegText:
			p.i++
			if seg.body != "" {
				nodes = append(nodes, &kvJjText{s: seg.body})
			}
		case kvJjSegComment:
			p.i++
		case kvJjSegOutput:
			p.i++
			ep, err := p.exprParser(seg.body, seg.pos)
			if err != nil {
				return nil, err
			}
			e, err := ep.parseTuple(true, false)
			if err == nil {
				err = ep.expectEnd()
			}
			if err != nil {
				return nil, err
			}
			nodes = append(nodes, &kvJjOutput{e: e, pos: seg.pos})
		case kvJjSegBlock:
			kw, _ := kvJjSplitKw(seg.body)
			for _, u := range until {
				if kw == u {
					return nodes, nil
				}
			}
			n, err := p.parseBlock(seg)
			if err != nil {
				return nil, err
			}
			nodes = append(nodes, n)
		}
	}
	if len(until) != 0 {
		return nil, kvJjErrf(0, "unexpected end of template (missing %s)", until[len(until)-1])
	}
	return nodes, nil
}

func kvJjSplitKw(body string) (string, string) {
	if sp := strings.IndexAny(body, " \t\r\n"); sp >= 0 {
		return body[:sp], strings.TrimSpace(body[sp:])
	}
	return body, ""
}

func (p *kvJjSegParser) exprParser(src string, pos int) (*kvJjExprParser, error) {
	toks, err := kvJjLexExpr(src, pos)
	if err != nil {
		return nil, err
	}
	return &kvJjExprParser{toks: toks, names: p.names}, nil
}

func (p *kvJjSegParser) parseBlock(seg kvJjSeg) (kvJjNode, error) {
	kw, rest := kvJjSplitKw(seg.body)
	p.i++
	switch kw {
	case "if":
		return p.parseIf(rest, seg.pos)
	case "for":
		return p.parseFor(rest, seg.pos)
	case "set":
		return p.parseSet(rest, seg.pos)
	case "macro":
		return p.parseMacro(rest, seg.pos)
	case "continue", "break":
		if rest != "" {
			return nil, kvJjErrf(seg.pos, "%s takes no arguments", kw)
		}
		if p.loopDepth == 0 {
			return nil, kvJjErrf(seg.pos, "%s outside of a loop", kw)
		}
		return &kvJjLoopCtl{brk: kw == "break"}, nil
	}
	return nil, kvJjErrf(seg.pos, "unsupported block %q", kw)
}

// expectTerm consumes the terminator tag parseBody stopped at and returns
// its keyword and remainder.
func (p *kvJjSegParser) expectTerm() (string, string, int) {
	term := p.segs[p.i]
	p.i++
	kw, rest := kvJjSplitKw(term.body)
	return kw, rest, term.pos
}

func (p *kvJjSegParser) parseIf(condSrc string, pos int) (kvJjNode, error) {
	n := &kvJjIf{}
	for {
		ep, err := p.exprParser(condSrc, pos)
		if err != nil {
			return nil, err
		}
		cond, err := ep.parseTuple(true, false)
		if err == nil {
			err = ep.expectEnd()
		}
		if err != nil {
			return nil, err
		}
		body, err := p.parseBody([]string{"elif", "else", "endif"})
		if err != nil {
			return nil, err
		}
		n.conds = append(n.conds, cond)
		n.bodies = append(n.bodies, body)
		kw, rest, tpos := p.expectTerm()
		switch kw {
		case "endif":
			return n, nil
		case "elif":
			condSrc, pos = rest, tpos
		case "else":
			els, err := p.parseBody([]string{"endif"})
			if err != nil {
				return nil, err
			}
			n.els = els
			p.i++ // consume endif
			return n, nil
		}
	}
}

// parseTargets parses an assignment target list: name (, name)*.
func (ep *kvJjExprParser) parseTargets() ([]string, error) {
	var names []string
	for {
		t := ep.next()
		if t.kind != "ident" || kvJjReserved[t.s] {
			return nil, kvJjErrf(t.pos, "unsupported assignment target %q", t.s)
		}
		names = append(names, t.s)
		if !ep.accept("op", ",") {
			return names, nil
		}
	}
}

func (p *kvJjSegParser) parseFor(head string, pos int) (kvJjNode, error) {
	ep, err := p.exprParser(head, pos)
	if err != nil {
		return nil, err
	}
	targets, err := ep.parseTargets()
	if err != nil {
		return nil, err
	}
	if !ep.accept("ident", "in") {
		return nil, kvJjErrf(pos, "for: expected \"<target> in <expr>\"")
	}
	seq, err := ep.parseTuple(false, false)
	if err != nil {
		return nil, err
	}
	n := &kvJjFor{targets: targets, seq: seq, pos: pos}
	if kvJjIsContentAccess(seq) {
		p.iteratesContent = true
	}
	if ep.accept("ident", "if") {
		if n.filter, err = ep.parseExpression(true); err != nil {
			return nil, err
		}
	}
	if ep.cur().kind == "ident" && ep.cur().s == "recursive" {
		return nil, kvJjErrf(pos, "for: recursive loops are unsupported")
	}
	if err := ep.expectEnd(); err != nil {
		return nil, err
	}
	p.loopDepth++
	n.body, err = p.parseBody([]string{"else", "endfor"})
	p.loopDepth--
	if err != nil {
		return nil, err
	}
	if kw, _, _ := p.expectTerm(); kw == "else" {
		// The else body runs outside the loop: continue/break there is an
		// error in Jinja too.
		saved := p.loopDepth
		p.loopDepth = 0
		n.els, err = p.parseBody([]string{"endfor"})
		p.loopDepth = saved
		if err != nil {
			return nil, err
		}
		p.i++ // consume endfor
	}
	return n, nil
}

func (p *kvJjSegParser) parseSet(src string, pos int) (kvJjNode, error) {
	ep, err := p.exprParser(src, pos)
	if err != nil {
		return nil, err
	}
	first := ep.cur()
	if first.kind == "ident" && ep.toks[ep.i+1].kind == "op" && ep.toks[ep.i+1].s == "." {
		// Namespace attribute: ns.attr = expr
		ep.i += 2
		attr := ep.next()
		if attr.kind != "ident" {
			return nil, kvJjErrf(pos, "set: unsupported target")
		}
		if !ep.accept("op", "=") {
			return nil, kvJjErrf(pos, "set: expected \"=\"")
		}
		p.names[first.s] = true
		e, err := ep.parseTuple(true, false)
		if err == nil {
			err = ep.expectEnd()
		}
		if err != nil {
			return nil, err
		}
		return &kvJjSet{targets: []string{first.s}, attr: attr.s, e: e, pos: pos}, nil
	}
	targets, err := ep.parseTargets()
	if err != nil {
		return nil, err
	}
	if ep.cur().kind == "end" {
		// Block set: {% set x %}...{% endset %}
		if len(targets) != 1 {
			return nil, kvJjErrf(pos, "set: block assignment needs one name")
		}
		body, err := p.parseBody([]string{"endset"})
		if err != nil {
			return nil, err
		}
		p.i++ // consume endset
		return &kvJjSetBlock{name: targets[0], body: body}, nil
	}
	if !ep.accept("op", "=") {
		return nil, kvJjErrf(pos, "set: expected \"<target> = <expr>\"")
	}
	e, err := ep.parseTuple(true, false)
	if err == nil {
		err = ep.expectEnd()
	}
	if err != nil {
		return nil, err
	}
	return &kvJjSet{targets: targets, e: e, pos: pos}, nil
}

func (p *kvJjSegParser) parseMacro(src string, pos int) (kvJjNode, error) {
	ep, err := p.exprParser(src, pos)
	if err != nil {
		return nil, err
	}
	name := ep.next()
	if name.kind != "ident" || kvJjReserved[name.s] {
		return nil, kvJjErrf(pos, "macro: expected a name")
	}
	d := &kvJjMacroDecl{name: name.s, pos: pos}
	if !ep.accept("op", "(") {
		return nil, kvJjErrf(pos, "macro: expected a parameter list")
	}
	for !ep.accept("op", ")") {
		if len(d.params) > 0 && !ep.accept("op", ",") {
			return nil, kvJjErrf(ep.cur().pos, "macro: expected \",\"")
		}
		if ep.accept("op", ")") {
			break
		}
		pn := ep.next()
		if pn.kind != "ident" || kvJjReserved[pn.s] {
			return nil, kvJjErrf(pn.pos, "macro: bad parameter")
		}
		var def kvJjExpr
		if ep.accept("op", "=") {
			if def, err = ep.parseExpression(true); err != nil {
				return nil, err
			}
		} else if len(d.defaults) > 0 && d.defaults[len(d.defaults)-1] != nil {
			return nil, kvJjErrf(pn.pos, "macro: non-default parameter after a default one")
		}
		d.params = append(d.params, pn.s)
		d.defaults = append(d.defaults, def)
	}
	if err := ep.expectEnd(); err != nil {
		return nil, err
	}
	saved := p.loopDepth
	p.loopDepth = 0
	d.body, err = p.parseBody([]string{"endmacro"})
	p.loopDepth = saved
	if err != nil {
		return nil, err
	}
	p.i++ // consume endmacro
	return &kvJjMacroDef{decl: d}, nil
}

// ---------------------------------------------------------------------------
// Expression lexer + parser, following Jinja's grammar:
//   tuple      := expr (',' expr)* [',']
//   expression := or ['if' or ['else' expression]]
//   or/and/not, compare (== != < <= > >= in, not in),
//   math1 (+ -) < concat (~) < math2 (* / // %) < pow < unary,
//   unary := ('-' unary | primary postfix*) filter_expr*
// Filters, tests and calls bind at the unary level, so `-l|length` is
// `(-l)|length` and `a ~ b|trim` is `a ~ (b|trim)`.

type kvJjTok struct {
	kind string // ident, int, str, op, end
	s    string
	n    int
	pos  int
}

// kvJjReserved are keywords that can never be a variable name.
var kvJjReserved = map[string]bool{
	"and": true, "or": true, "not": true, "in": true, "is": true, "if": true, "else": true,
	"true": true, "false": true, "none": true, "True": true, "False": true, "None": true,
}

func kvJjLexExpr(src string, base int) ([]kvJjTok, error) {
	var toks []kvJjTok
	i := 0
	for i < len(src) {
		c := src[i]
		switch {
		case c == ' ' || c == '\t' || c == '\r' || c == '\n':
			i++
		case c == '\'' || c == '"':
			s, n, err := kvJjLexString(src[i:], base+i)
			if err != nil {
				return nil, err
			}
			toks = append(toks, kvJjTok{kind: "str", s: s, pos: base + i})
			i += n
		case c >= '0' && c <= '9':
			j := i
			for j < len(src) && (src[j] >= '0' && src[j] <= '9' || src[j] == '_') {
				j++
			}
			if j < len(src) && (src[j] == '.' && j+1 < len(src) && src[j+1] >= '0' && src[j+1] <= '9' || src[j] == 'e' || src[j] == 'E') {
				return nil, kvJjErrf(base+i, "float literals are unsupported")
			}
			n, err := strconv.Atoi(strings.ReplaceAll(src[i:j], "_", ""))
			if err != nil {
				return nil, kvJjErrf(base+i, "bad integer literal %q", src[i:j])
			}
			toks = append(toks, kvJjTok{kind: "int", n: n, pos: base + i})
			i = j
		case c == '_' || c >= 0x80 || unicode.IsLetter(rune(c)):
			j := i
			for j < len(src) {
				r := src[j]
				if r == '_' || r >= 0x80 || unicode.IsLetter(rune(r)) || unicode.IsDigit(rune(r)) {
					j++
					continue
				}
				break
			}
			toks = append(toks, kvJjTok{kind: "ident", s: src[i:j], pos: base + i})
			i = j
		default:
			two := ""
			if i+1 < len(src) {
				two = src[i : i+2]
			}
			switch two {
			case "==", "!=", "<=", ">=", "//", "**":
				toks = append(toks, kvJjTok{kind: "op", s: two, pos: base + i})
				i += 2
				continue
			}
			switch c {
			case '+', '-', '*', '/', '%', '<', '>', '(', ')', '[', ']', '{', '}', '.', ',', ':', '|', '=', '~':
				toks = append(toks, kvJjTok{kind: "op", s: string(c), pos: base + i})
				i++
			default:
				return nil, kvJjErrf(base+i, "unsupported character %q in expression", string(c))
			}
		}
	}
	toks = append(toks, kvJjTok{kind: "end", pos: base + len(src)})
	return toks, nil
}

// kvJjLexString decodes a quoted literal the way Jinja does: the body is
// passed through Python's unicode-escape codec, so \n \t \xNN \uNNNN
// \UNNNNNNNN \N{...} octal and \<newline> are escapes and an unknown escape
// is kept verbatim. Returns the value and the bytes consumed.
func kvJjLexString(src string, pos int) (string, int, error) {
	q := src[0]
	var b strings.Builder
	i := 1
	for i < len(src) {
		c := src[i]
		if c == q {
			return b.String(), i + 1, nil
		}
		if c != '\\' || i+1 >= len(src) {
			b.WriteByte(c)
			i++
			continue
		}
		e := src[i+1]
		i += 2
		switch e {
		case '\n':
		case '\\':
			b.WriteByte('\\')
		case '\'':
			b.WriteByte('\'')
		case '"':
			b.WriteByte('"')
		case 'a':
			b.WriteByte('\a')
		case 'b':
			b.WriteByte('\b')
		case 'f':
			b.WriteByte('\f')
		case 'n':
			b.WriteByte('\n')
		case 'r':
			b.WriteByte('\r')
		case 't':
			b.WriteByte('\t')
		case 'v':
			b.WriteByte('\v')
		case 'x', 'u', 'U':
			width := map[byte]int{'x': 2, 'u': 4, 'U': 8}[e]
			if i+width > len(src) {
				return "", 0, kvJjErrf(pos, "truncated \\%c escape", e)
			}
			v, err := strconv.ParseUint(src[i:i+width], 16, 32)
			if err != nil || v > unicode.MaxRune {
				return "", 0, kvJjErrf(pos, "bad \\%c escape", e)
			}
			b.WriteRune(rune(v))
			i += width
		case '0', '1', '2', '3', '4', '5', '6', '7':
			v := int(e - '0')
			for k := 0; k < 2 && i < len(src) && src[i] >= '0' && src[i] <= '7'; k++ {
				v = v*8 + int(src[i]-'0')
				i++
			}
			b.WriteRune(rune(v))
		case 'N':
			return "", 0, kvJjErrf(pos, "\\N{...} escapes are unsupported")
		default:
			b.WriteByte('\\')
			b.WriteByte(e)
		}
	}
	return "", 0, kvJjErrf(pos, "unterminated string literal")
}

type kvJjExpr interface {
	eval(rt *kvJjRT) (any, error)
}

type kvJjExprParser struct {
	toks  []kvJjTok
	i     int
	names map[string]bool
}

// kvJjParseExprAll parses a complete standalone expression.
func kvJjParseExprAll(src string, base int) (kvJjExpr, error) {
	toks, err := kvJjLexExpr(src, base)
	if err != nil {
		return nil, err
	}
	p := &kvJjExprParser{toks: toks, names: map[string]bool{}}
	e, err := p.parseTuple(true, false)
	if err != nil {
		return nil, err
	}
	return e, p.expectEnd()
}

func (p *kvJjExprParser) cur() kvJjTok  { return p.toks[p.i] }
func (p *kvJjExprParser) peek() kvJjTok { return p.toks[min(p.i+1, len(p.toks)-1)] }
func (p *kvJjExprParser) next() kvJjTok {
	t := p.toks[p.i]
	if t.kind != "end" {
		p.i++
	}
	return t
}

func (p *kvJjExprParser) accept(kind, s string) bool {
	t := p.cur()
	if t.kind == kind && (s == "" || t.s == s) {
		p.i++
		return true
	}
	return false
}

func (p *kvJjExprParser) expectEnd() error {
	if t := p.cur(); t.kind != "end" {
		return kvJjErrf(t.pos, "unexpected %q after expression", t.s)
	}
	return nil
}

func (p *kvJjExprParser) atTupleEnd() bool {
	t := p.cur()
	if t.kind == "end" {
		return true
	}
	if t.kind == "op" && (t.s == ")" || t.s == "]" || t.s == "}" || t.s == "=" || t.s == ":") {
		return true
	}
	return t.kind == "ident" && (t.s == "if" || t.s == "in" || t.s == "else" || t.s == "recursive")
}

// parseTuple parses a possibly comma-separated expression list; a single
// expression without a trailing comma is returned as itself.
func (p *kvJjExprParser) parseTuple(withCondexpr, explicitParens bool) (kvJjExpr, error) {
	var items []kvJjExpr
	isTuple := false
	for {
		if len(items) > 0 {
			if !p.accept("op", ",") {
				break
			}
			isTuple = true
		}
		if p.atTupleEnd() {
			break
		}
		e, err := p.parseExpression(withCondexpr)
		if err != nil {
			return nil, err
		}
		items = append(items, e)
	}
	if !isTuple {
		if len(items) == 0 {
			if explicitParens {
				return &kvJjSeqLit{tuple: true}, nil
			}
			return nil, kvJjErrf(p.cur().pos, "expected an expression")
		}
		return items[0], nil
	}
	return &kvJjSeqLit{items: items, tuple: true}, nil
}

func (p *kvJjExprParser) parseExpression(withCondexpr bool) (kvJjExpr, error) {
	if !withCondexpr {
		return p.parseOr()
	}
	e, err := p.parseOr()
	if err != nil {
		return nil, err
	}
	for p.accept("ident", "if") {
		cond, err := p.parseOr()
		if err != nil {
			return nil, err
		}
		var els kvJjExpr
		if p.accept("ident", "else") {
			if els, err = p.parseExpression(true); err != nil {
				return nil, err
			}
		}
		e = &kvJjCond{cond: cond, a: e, b: els}
	}
	return e, nil
}

func (p *kvJjExprParser) parseOr() (kvJjExpr, error) {
	l, err := p.parseAnd()
	if err != nil {
		return nil, err
	}
	for p.accept("ident", "or") {
		r, err := p.parseAnd()
		if err != nil {
			return nil, err
		}
		l = &kvJjBool{op: "or", l: l, r: r}
	}
	return l, nil
}

func (p *kvJjExprParser) parseAnd() (kvJjExpr, error) {
	l, err := p.parseNot()
	if err != nil {
		return nil, err
	}
	for p.accept("ident", "and") {
		r, err := p.parseNot()
		if err != nil {
			return nil, err
		}
		l = &kvJjBool{op: "and", l: l, r: r}
	}
	return l, nil
}

func (p *kvJjExprParser) parseNot() (kvJjExpr, error) {
	if p.accept("ident", "not") {
		e, err := p.parseNot()
		if err != nil {
			return nil, err
		}
		return &kvJjNot{e: e}, nil
	}
	return p.parseCompare()
}

func (p *kvJjExprParser) parseCompare() (kvJjExpr, error) {
	l, err := p.parseMath1()
	if err != nil {
		return nil, err
	}
	for ops := 0; ; ops++ {
		t := p.cur()
		var op string
		switch {
		case t.kind == "op" && (t.s == "==" || t.s == "!=" || t.s == "<" || t.s == "<=" || t.s == ">" || t.s == ">="):
			op = t.s
			p.i++
		case t.kind == "ident" && t.s == "in":
			op = "in"
			p.i++
		case t.kind == "ident" && t.s == "not" && p.peek().kind == "ident" && p.peek().s == "in":
			op = "notin"
			p.i += 2
		default:
			return l, nil
		}
		if ops > 0 {
			// a < b < c means (a < b) and (b < c) in Jinja; not modelled.
			return nil, kvJjErrf(t.pos, "chained comparisons are unsupported")
		}
		r, err := p.parseMath1()
		if err != nil {
			return nil, err
		}
		l = &kvJjCmp{op: op, l: l, r: r, pos: t.pos}
	}
}

func (p *kvJjExprParser) parseBinary(ops []string, sub func() (kvJjExpr, error)) (kvJjExpr, error) {
	l, err := sub()
	if err != nil {
		return nil, err
	}
	for {
		t := p.cur()
		matched := false
		for _, o := range ops {
			if t.kind == "op" && t.s == o {
				matched = true
			}
		}
		if !matched {
			return l, nil
		}
		p.i++
		r, err := sub()
		if err != nil {
			return nil, err
		}
		l = &kvJjArith{op: t.s, l: l, r: r, pos: t.pos}
	}
}

func (p *kvJjExprParser) parseMath1() (kvJjExpr, error) {
	return p.parseBinary([]string{"+", "-"}, p.parseConcat)
}

func (p *kvJjExprParser) parseConcat() (kvJjExpr, error) {
	return p.parseBinary([]string{"~"}, p.parseMath2)
}

func (p *kvJjExprParser) parseMath2() (kvJjExpr, error) {
	return p.parseBinary([]string{"*", "/", "//", "%"}, p.parsePow)
}

func (p *kvJjExprParser) parsePow() (kvJjExpr, error) {
	e, err := p.parseUnary(true)
	if err != nil {
		return nil, err
	}
	if t := p.cur(); t.kind == "op" && t.s == "**" {
		return nil, kvJjErrf(t.pos, "operator ** is unsupported")
	}
	return e, nil
}

func (p *kvJjExprParser) parseUnary(withFilter bool) (kvJjExpr, error) {
	var e kvJjExpr
	var err error
	t := p.cur()
	switch {
	case t.kind == "op" && t.s == "-":
		p.i++
		inner, err := p.parseUnary(false)
		if err != nil {
			return nil, err
		}
		e = &kvJjNeg{e: inner, pos: t.pos}
	case t.kind == "op" && t.s == "+":
		return nil, kvJjErrf(t.pos, "unary + is unsupported")
	default:
		if e, err = p.parsePrimary(); err != nil {
			return nil, err
		}
	}
	if e, err = p.parsePostfix(e); err != nil {
		return nil, err
	}
	if withFilter {
		return p.parseFilterExpr(e)
	}
	return e, nil
}

func (p *kvJjExprParser) parsePrimary() (kvJjExpr, error) {
	t := p.next()
	switch t.kind {
	case "str":
		s := t.s
		for p.cur().kind == "str" {
			s += p.next().s
		}
		return &kvJjLit{v: s}, nil
	case "int":
		return &kvJjLit{v: t.n}, nil
	case "ident":
		switch t.s {
		case "true", "True":
			return &kvJjLit{v: true}, nil
		case "false", "False":
			return &kvJjLit{v: false}, nil
		case "none", "None":
			return &kvJjLit{v: nil}, nil
		}
		if kvJjReserved[t.s] {
			return nil, kvJjErrf(t.pos, "unexpected keyword %q", t.s)
		}
		p.names[t.s] = true
		return &kvJjVar{name: t.s, pos: t.pos}, nil
	case "op":
		switch t.s {
		case "(":
			e, err := p.parseTuple(true, true)
			if err != nil {
				return nil, err
			}
			if !p.accept("op", ")") {
				return nil, kvJjErrf(t.pos, "missing \")\"")
			}
			return e, nil
		case "[":
			var items []kvJjExpr
			for !p.accept("op", "]") {
				if len(items) > 0 && !p.accept("op", ",") {
					return nil, kvJjErrf(p.cur().pos, "list: expected \",\"")
				}
				if p.accept("op", "]") {
					break
				}
				e, err := p.parseExpression(true)
				if err != nil {
					return nil, err
				}
				items = append(items, e)
			}
			return &kvJjSeqLit{items: items}, nil
		case "{":
			d := &kvJjDictLit{}
			for !p.accept("op", "}") {
				if len(d.keys) > 0 && !p.accept("op", ",") {
					return nil, kvJjErrf(p.cur().pos, "dict: expected \",\"")
				}
				if p.accept("op", "}") {
					break
				}
				k, err := p.parseExpression(true)
				if err != nil {
					return nil, err
				}
				if !p.accept("op", ":") {
					return nil, kvJjErrf(p.cur().pos, "dict: expected \":\"")
				}
				v, err := p.parseExpression(true)
				if err != nil {
					return nil, err
				}
				d.keys = append(d.keys, k)
				d.vals = append(d.vals, v)
			}
			d.pos = t.pos
			return d, nil
		}
	}
	return nil, kvJjErrf(t.pos, "unexpected token %q", t.s)
}

func (p *kvJjExprParser) parsePostfix(e kvJjExpr) (kvJjExpr, error) {
	for {
		t := p.cur()
		switch {
		case t.kind == "op" && t.s == ".":
			p.i++
			name := p.next()
			switch name.kind {
			case "ident":
				e = &kvJjAttr{obj: e, name: name.s, pos: name.pos}
			case "int":
				e = &kvJjIndex{obj: e, idx: &kvJjLit{v: name.n}, pos: name.pos}
			default:
				return nil, kvJjErrf(name.pos, "expected attribute name after \".\"")
			}
		case t.kind == "op" && t.s == "[":
			p.i++
			var err error
			if e, err = p.parseSubscript(e, t.pos); err != nil {
				return nil, err
			}
		case t.kind == "op" && t.s == "(":
			p.i++
			args, err := p.parseCallArgs()
			if err != nil {
				return nil, err
			}
			e = &kvJjCall{fn: e, args: args, pos: t.pos}
		default:
			return e, nil
		}
	}
}

func (p *kvJjExprParser) parseFilterExpr(e kvJjExpr) (kvJjExpr, error) {
	for {
		t := p.cur()
		switch {
		case t.kind == "op" && t.s == "|":
			p.i++
			name := p.next()
			if name.kind != "ident" {
				return nil, kvJjErrf(name.pos, "expected filter name after \"|\"")
			}
			f := &kvJjFilter{e: e, name: name.s, pos: name.pos}
			if _, ok := kvJjFilters[name.s]; !ok {
				// Jinja resolves filters at compile time.
				return nil, kvJjErrf(name.pos, "unsupported filter %q", name.s)
			}
			if p.accept("op", "(") {
				var err error
				if f.args, err = p.parseCallArgs(); err != nil {
					return nil, err
				}
			}
			e = f
		case t.kind == "ident" && t.s == "is":
			p.i++
			negate := p.accept("ident", "not")
			name := p.next()
			if name.kind != "ident" && !(name.kind == "op" && (name.s == "==" || name.s == "!=" || name.s == "<" || name.s == "<=" || name.s == ">" || name.s == ">=")) {
				return nil, kvJjErrf(name.pos, "expected test name after \"is\"")
			}
			te := &kvJjTest{e: e, name: name.s, negate: negate, pos: name.pos}
			c := p.cur()
			if p.accept("op", "(") {
				args, err := p.parseCallArgs()
				if err != nil {
					return nil, err
				}
				if len(args.kw) != 0 {
					return nil, kvJjErrf(name.pos, "keyword arguments to tests are unsupported")
				}
				te.args = args.pos
			} else if c.kind == "str" || c.kind == "int" || (c.kind == "op" && (c.s == "(" || c.s == "[" || c.s == "{")) ||
				(c.kind == "ident" && c.s != "else" && c.s != "or" && c.s != "and" && c.s != "if" && c.s != "is" && c.s != "in" && c.s != "not") {
				arg, err := p.parsePrimary()
				if err != nil {
					return nil, err
				}
				if arg, err = p.parsePostfix(arg); err != nil {
					return nil, err
				}
				te.args = []kvJjExpr{arg}
			}
			e = te
		case t.kind == "op" && t.s == "(":
			p.i++
			args, err := p.parseCallArgs()
			if err != nil {
				return nil, err
			}
			e = &kvJjCall{fn: e, args: args, pos: t.pos}
		default:
			return e, nil
		}
	}
}

type kvJjCallArgs struct {
	pos    []kvJjExpr
	kw     []string
	kwVals []kvJjExpr
}

// parseCallArgs parses "(a, b, k=v)" after the opening parenthesis.
func (p *kvJjExprParser) parseCallArgs() (*kvJjCallArgs, error) {
	a := &kvJjCallArgs{}
	first := true
	for !p.accept("op", ")") {
		if !first && !p.accept("op", ",") {
			return nil, kvJjErrf(p.cur().pos, "expected \",\" or \")\" in argument list")
		}
		first = false
		if p.accept("op", ")") {
			break
		}
		if t := p.cur(); t.kind == "op" && (t.s == "*" || t.s == "**") {
			return nil, kvJjErrf(t.pos, "*args/**kwargs calls are unsupported")
		}
		if t := p.cur(); t.kind == "ident" && p.peek().kind == "op" && p.peek().s == "=" {
			p.i += 2
			v, err := p.parseExpression(true)
			if err != nil {
				return nil, err
			}
			for _, k := range a.kw {
				if k == t.s {
					return nil, kvJjErrf(t.pos, "duplicate keyword argument %q", t.s)
				}
			}
			a.kw = append(a.kw, t.s)
			a.kwVals = append(a.kwVals, v)
			continue
		}
		if len(a.kw) > 0 {
			return nil, kvJjErrf(p.cur().pos, "positional argument after keyword argument")
		}
		v, err := p.parseExpression(true)
		if err != nil {
			return nil, err
		}
		a.pos = append(a.pos, v)
	}
	return a, nil
}

func (p *kvJjExprParser) parseSubscript(obj kvJjExpr, pos int) (kvJjExpr, error) {
	var parts [3]kvJjExpr
	slot := 0
	isSlice := false
	for {
		t := p.cur()
		if t.kind == "op" && t.s == ":" {
			p.i++
			isSlice = true
			slot++
			if slot > 2 {
				return nil, kvJjErrf(t.pos, "too many slice separators")
			}
			continue
		}
		if t.kind == "op" && t.s == "]" {
			p.i++
			break
		}
		if parts[slot] != nil {
			return nil, kvJjErrf(t.pos, "unsupported subscript")
		}
		e, err := p.parseExpression(true)
		if err != nil {
			return nil, err
		}
		parts[slot] = e
	}
	if !isSlice {
		if parts[0] == nil {
			return nil, kvJjErrf(pos, "empty subscript")
		}
		return &kvJjIndex{obj: obj, idx: parts[0], pos: pos}, nil
	}
	return &kvJjSlice{obj: obj, start: parts[0], stop: parts[1], step: parts[2], pos: pos}, nil
}

// ---------------------------------------------------------------------------
// Expression nodes.

type kvJjLit struct{ v any }

type kvJjVar struct {
	name string
	pos  int
}

type kvJjBool struct {
	op   string
	l, r kvJjExpr
}

type kvJjNot struct{ e kvJjExpr }

type kvJjCmp struct {
	op   string // == != < <= > >= in notin
	l, r kvJjExpr
	pos  int
}

type kvJjArith struct {
	op   string
	l, r kvJjExpr
	pos  int
}

type kvJjNeg struct {
	e   kvJjExpr
	pos int
}

type kvJjCond struct {
	cond, a, b kvJjExpr // b nil: Undefined when the condition is false
}

type kvJjSeqLit struct {
	items []kvJjExpr
	tuple bool
}

type kvJjDictLit struct {
	keys, vals []kvJjExpr
	pos        int
}

type kvJjAttr struct {
	obj  kvJjExpr
	name string
	pos  int
}

type kvJjIndex struct {
	obj, idx kvJjExpr
	pos      int
}

type kvJjSlice struct {
	obj               kvJjExpr
	start, stop, step kvJjExpr
	pos               int
}

type kvJjCall struct {
	fn   kvJjExpr
	args *kvJjCallArgs
	pos  int
}

type kvJjFilter struct {
	e    kvJjExpr
	name string
	args *kvJjCallArgs
	pos  int
}

type kvJjTest struct {
	e      kvJjExpr
	name   string
	args   []kvJjExpr
	negate bool
	pos    int
}

// ---------------------------------------------------------------------------
// Runtime.

// kvJjMaxCallDepth bounds macro recursion (Python's own recursion limit is
// what stops a runaway template engine-side; the gateway refuses earlier).
const kvJjMaxCallDepth = 64

type kvJjRT struct {
	scopes []map[string]any
	root   map[string]any // the template's top-level frame, shared by macros
	depth  int
}

func (rt *kvJjRT) lookup(name string) (any, bool) {
	for i := len(rt.scopes) - 1; i >= 0; i-- {
		if v, ok := rt.scopes[i][name]; ok {
			return v, true
		}
	}
	return nil, false
}

// set writes the innermost scope: Jinja assignments never escape a for-loop
// or macro frame (templates use namespace() when they need that), while
// assignments inside {% if %} blocks share the enclosing frame.
func (rt *kvJjRT) set(name string, v any) {
	rt.scopes[len(rt.scopes)-1][name] = v
}

// Render executes the template. ctx values use Go types (string, int, bool,
// nil, []any, map[string]any — keys taken in sorted order) or the executor's
// own value model (*kvJjDict for insertion-ordered dicts, *kvJjBuiltin).
func (t *kvJinjaTemplate) Render(ctx map[string]any) (string, error) {
	vars := make(map[string]any, len(ctx))
	for k, v := range ctx {
		vars[k] = kvJjFromGo(v)
	}
	root := map[string]any{}
	rt := &kvJjRT{scopes: []map[string]any{kvJjGlobals, vars, root}, root: root}
	var sb strings.Builder
	if err := kvJjExecBody(rt, t.nodes, &sb); err != nil {
		return "", err
	}
	return sb.String(), nil
}

func kvJjExecBody(rt *kvJjRT, nodes []kvJjNode, sb *strings.Builder) error {
	for _, n := range nodes {
		if err := n.exec(rt, sb); err != nil {
			return err
		}
	}
	return nil
}

func (n *kvJjText) exec(rt *kvJjRT, sb *strings.Builder) error {
	sb.WriteString(n.s)
	return nil
}

func (n *kvJjOutput) exec(rt *kvJjRT, sb *strings.Builder) error {
	v, err := n.e.eval(rt)
	if err != nil {
		return err
	}
	s, err := kvJjToStr(v)
	if err != nil {
		return kvJjAt(n.pos, err)
	}
	sb.WriteString(s)
	return nil
}

func (n *kvJjIf) exec(rt *kvJjRT, sb *strings.Builder) error {
	for i, cond := range n.conds {
		v, err := cond.eval(rt)
		if err != nil {
			return err
		}
		if kvJjTruthy(v) {
			return kvJjExecBody(rt, n.bodies[i], sb)
		}
	}
	return kvJjExecBody(rt, n.els, sb)
}

func kvJjAssign(frame map[string]any, targets []string, v any, pos int) error {
	if len(targets) == 1 {
		frame[targets[0]] = v
		return nil
	}
	items, err := kvJjIter(v)
	if err != nil {
		return kvJjAt(pos, err)
	}
	if _, ok := v.(kvJjUndef); ok {
		return kvJjErrf(pos, "cannot unpack undefined value")
	}
	if len(items) != len(targets) {
		return kvJjErrf(pos, "cannot unpack %d values into %d targets", len(items), len(targets))
	}
	for i, t := range targets {
		frame[t] = items[i]
	}
	return nil
}

func (n *kvJjFor) exec(rt *kvJjRT, sb *strings.Builder) error {
	seq, err := n.seq.eval(rt)
	if err != nil {
		return err
	}
	all, err := kvJjIter(seq)
	if err != nil {
		return kvJjAt(n.pos, err)
	}
	items := all
	if n.filter != nil {
		items = nil
		for _, it := range all {
			frame := map[string]any{}
			if err := kvJjAssign(frame, n.targets, it, n.pos); err != nil {
				return err
			}
			rt.scopes = append(rt.scopes, frame)
			ok, err := n.filter.eval(rt)
			rt.scopes = rt.scopes[:len(rt.scopes)-1]
			if err != nil {
				return err
			}
			if kvJjTruthy(ok) {
				items = append(items, it)
			}
		}
	}
	for idx, item := range items {
		loop := kvJjNewDict()
		loop.set("index0", idx)
		loop.set("index", idx+1)
		loop.set("revindex", len(items)-idx)
		loop.set("revindex0", len(items)-idx-1)
		loop.set("first", idx == 0)
		loop.set("last", idx == len(items)-1)
		loop.set("length", len(items))
		loop.set("depth", 1)
		loop.set("depth0", 0)
		if idx > 0 {
			loop.set("previtem", items[idx-1])
		}
		if idx+1 < len(items) {
			loop.set("nextitem", items[idx+1])
		}
		frame := map[string]any{"loop": loop}
		if err := kvJjAssign(frame, n.targets, item, n.pos); err != nil {
			return err
		}
		rt.scopes = append(rt.scopes, frame)
		err := kvJjExecBody(rt, n.body, sb)
		rt.scopes = rt.scopes[:len(rt.scopes)-1]
		if errors.Is(err, kvJjContinueSig) {
			continue
		}
		if errors.Is(err, kvJjBreakSig) {
			break
		}
		if err != nil {
			return err
		}
	}
	if len(items) == 0 {
		return kvJjExecBody(rt, n.els, sb)
	}
	return nil
}

func (n *kvJjLoopCtl) exec(rt *kvJjRT, sb *strings.Builder) error {
	if n.brk {
		return kvJjBreakSig
	}
	return kvJjContinueSig
}

func (n *kvJjSet) exec(rt *kvJjRT, sb *strings.Builder) error {
	v, err := n.e.eval(rt)
	if err != nil {
		return err
	}
	if n.attr == "" {
		return kvJjAssign(rt.scopes[len(rt.scopes)-1], n.targets, v, n.pos)
	}
	cur, ok := rt.lookup(n.targets[0])
	if !ok {
		return kvJjErrf(n.pos, "set: %q is undefined", n.targets[0])
	}
	ns, ok := cur.(*kvJjNS)
	if !ok {
		return kvJjErrf(n.pos, "set: %q is not a namespace", n.targets[0])
	}
	ns.attrs[n.attr] = v
	return nil
}

func (n *kvJjSetBlock) exec(rt *kvJjRT, sb *strings.Builder) error {
	var inner strings.Builder
	if err := kvJjExecBody(rt, n.body, &inner); err != nil {
		return err
	}
	rt.set(n.name, inner.String())
	return nil
}

func (n *kvJjMacroDef) exec(rt *kvJjRT, sb *strings.Builder) error {
	rt.set(n.decl.name, &kvJjMacro{decl: n.decl})
	return nil
}

// call binds arguments and renders the macro body. The body sees the render
// context and the template's top-level variables as they are at call time,
// never the caller's loop or local variables.
func (m *kvJjMacro) call(rt *kvJjRT, a *kvJjArgs) (any, error) {
	d := m.decl
	if len(a.pos) > len(d.params) {
		return nil, kvJjErrf(d.pos, "macro %q takes not more than %d argument(s)", d.name, len(d.params))
	}
	if rt.depth >= kvJjMaxCallDepth {
		return nil, kvJjErrf(d.pos, "macro %q: recursion too deep", d.name)
	}
	frame := map[string]any{}
	for _, k := range a.kw {
		idx := -1
		for i, p := range d.params {
			if p == k.name {
				idx = i
			}
		}
		if idx < 0 {
			return nil, kvJjErrf(d.pos, "macro %q takes no keyword argument %q", d.name, k.name)
		}
		if idx < len(a.pos) {
			return nil, kvJjErrf(d.pos, "macro %q got multiple values for argument %q", d.name, k.name)
		}
	}
	sub := &kvJjRT{scopes: []map[string]any{rt.scopes[0], rt.scopes[1], rt.root, frame}, root: rt.root, depth: rt.depth + 1}
	for i, p := range d.params {
		if v, ok := a.arg(i, p, nil); ok {
			frame[p] = v
			continue
		}
		if d.defaults[i] != nil {
			v, err := d.defaults[i].eval(sub)
			if err != nil {
				return nil, err
			}
			frame[p] = v
			continue
		}
		frame[p] = kvJjUndef{name: p}
	}
	var sb strings.Builder
	if err := kvJjExecBody(sub, d.body, &sb); err != nil {
		return nil, err
	}
	return sb.String(), nil
}

// ---------------------------------------------------------------------------
// Evaluation.

func (e *kvJjLit) eval(rt *kvJjRT) (any, error) { return e.v, nil }

func (e *kvJjVar) eval(rt *kvJjRT) (any, error) {
	if v, ok := rt.lookup(e.name); ok {
		return v, nil
	}
	return kvJjUndef{name: e.name}, nil
}

func (e *kvJjBool) eval(rt *kvJjRT) (any, error) {
	l, err := e.l.eval(rt)
	if err != nil {
		return nil, err
	}
	// Jinja and/or return an operand, not a bool — short-circuit included.
	if e.op == "and" {
		if !kvJjTruthy(l) {
			return l, nil
		}
		return e.r.eval(rt)
	}
	if kvJjTruthy(l) {
		return l, nil
	}
	return e.r.eval(rt)
}

func (e *kvJjNot) eval(rt *kvJjRT) (any, error) {
	v, err := e.e.eval(rt)
	if err != nil {
		return nil, err
	}
	return !kvJjTruthy(v), nil
}

func (e *kvJjCmp) eval(rt *kvJjRT) (any, error) {
	l, err := e.l.eval(rt)
	if err != nil {
		return nil, err
	}
	r, err := e.r.eval(rt)
	if err != nil {
		return nil, err
	}
	switch e.op {
	case "==":
		return kvJjEqual(l, r), nil
	case "!=":
		return !kvJjEqual(l, r), nil
	case "in", "notin":
		in, err := kvJjContains(r, l)
		if err != nil {
			return nil, kvJjAt(e.pos, err)
		}
		return in == (e.op == "in"), nil
	}
	ok, err := kvJjOrder(e.op, l, r)
	return ok, kvJjAt(e.pos, err)
}

func (e *kvJjArith) eval(rt *kvJjRT) (any, error) {
	l, err := e.l.eval(rt)
	if err != nil {
		return nil, err
	}
	r, err := e.r.eval(rt)
	if err != nil {
		return nil, err
	}
	v, err := kvJjBinOp(e.op, l, r)
	return v, kvJjAt(e.pos, err)
}

func kvJjBinOp(op string, l, r any) (any, error) {
	if op == "~" {
		ls, err := kvJjToStr(l)
		if err != nil {
			return nil, err
		}
		rs, err := kvJjToStr(r)
		if err != nil {
			return nil, err
		}
		return ls + rs, nil
	}
	if _, u := l.(kvJjUndef); u {
		return nil, fmt.Errorf("%q is undefined", l.(kvJjUndef).name)
	}
	if _, u := r.(kvJjUndef); u {
		return nil, fmt.Errorf("%q is undefined", r.(kvJjUndef).name)
	}
	li, lnum := kvJjNum(l)
	ri, rnum := kvJjNum(r)
	if lnum && rnum {
		switch op {
		case "+":
			return li + ri, nil
		case "-":
			return li - ri, nil
		case "*":
			return li * ri, nil
		case "//", "%":
			if ri == 0 {
				return nil, fmt.Errorf("integer division or modulo by zero")
			}
			q, m := li/ri, li%ri
			if m != 0 && (m < 0) != (ri < 0) {
				q--
				m += ri
			}
			if op == "//" {
				return q, nil
			}
			return m, nil
		}
		return nil, fmt.Errorf("operator %q yields a float, which is unsupported", op)
	}
	_, lm := l.(kvJjMarkup)
	_, rm := r.(kvJjMarkup)
	switch op {
	case "+":
		if lm || rm {
			return nil, fmt.Errorf("+ on markup escapes its operand; unsupported")
		}
		if ls, ok := l.(string); ok {
			if rs, ok := r.(string); ok {
				return ls + rs, nil
			}
		}
		if la, ok := l.([]any); ok {
			if ra, ok := r.([]any); ok {
				return append(append([]any{}, la...), ra...), nil
			}
		}
		if la, ok := l.(kvJjTuple); ok {
			if ra, ok := r.(kvJjTuple); ok {
				return append(append(kvJjTuple{}, la...), ra...), nil
			}
		}
	case "*":
		seq, n := l, ri
		if lnum && !rnum {
			seq, n = r, li
		} else if !rnum {
			break
		}
		if lm || rm {
			return nil, fmt.Errorf("* on markup is unsupported")
		}
		if n < 0 {
			n = 0
		}
		if s, ok := seq.(string); ok {
			return strings.Repeat(s, n), nil
		}
		if la, ok := seq.([]any); ok {
			out := []any{}
			for i := 0; i < n; i++ {
				out = append(out, la...)
			}
			return out, nil
		}
	case "%":
		if _, ok := kvJjStr(l); ok {
			return nil, fmt.Errorf("printf-style string formatting is unsupported")
		}
	}
	return nil, fmt.Errorf("unsupported operand types for %s: %s and %s", op, kvJjTypeName(l), kvJjTypeName(r))
}

func (e *kvJjNeg) eval(rt *kvJjRT) (any, error) {
	v, err := e.e.eval(rt)
	if err != nil {
		return nil, err
	}
	i, ok := kvJjNum(v)
	if !ok {
		return nil, kvJjErrf(e.pos, "bad operand type for unary -: %s", kvJjTypeName(v))
	}
	return -i, nil
}

func (e *kvJjCond) eval(rt *kvJjRT) (any, error) {
	c, err := e.cond.eval(rt)
	if err != nil {
		return nil, err
	}
	if kvJjTruthy(c) {
		return e.a.eval(rt)
	}
	if e.b == nil {
		return kvJjUndef{name: "conditional"}, nil
	}
	return e.b.eval(rt)
}

func (e *kvJjSeqLit) eval(rt *kvJjRT) (any, error) {
	out := make([]any, len(e.items))
	for i, it := range e.items {
		v, err := it.eval(rt)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	if e.tuple {
		return kvJjTuple(out), nil
	}
	return out, nil
}

func (e *kvJjDictLit) eval(rt *kvJjRT) (any, error) {
	d := kvJjNewDict()
	for i := range e.keys {
		k, err := e.keys[i].eval(rt)
		if err != nil {
			return nil, err
		}
		ks, ok := kvJjStr(k)
		if !ok {
			return nil, kvJjErrf(e.pos, "dict keys must be strings, got %s", kvJjTypeName(k))
		}
		v, err := e.vals[i].eval(rt)
		if err != nil {
			return nil, err
		}
		d.set(ks, v)
	}
	return d, nil
}

func (e *kvJjAttr) eval(rt *kvJjRT) (any, error) {
	obj, err := e.obj.eval(rt)
	if err != nil {
		return nil, err
	}
	v, err := kvJjGetAttr(obj, e.name)
	return v, kvJjAt(e.pos, err)
}

// kvJjGetAttr is Jinja's sandboxed getattr: a Python attribute first (a
// method becomes a bound method value), then the item of the same name,
// else Undefined. Only Undefined itself raises.
func kvJjGetAttr(obj any, name string) (any, error) {
	switch o := obj.(type) {
	case kvJjUndef:
		return nil, fmt.Errorf("%q is undefined", o.name)
	case *kvJjDict:
		if kvJjHasAttrName(kvJjDictAttrs, name) {
			return &kvJjBound{obj: o, name: name}, nil
		}
		if v, ok := o.get(name); ok {
			return v, nil
		}
		return kvJjUndef{name: name}, nil
	case *kvJjNS:
		if v, ok := o.attrs[name]; ok {
			return v, nil
		}
		return kvJjUndef{name: name}, nil
	case string, kvJjMarkup:
		if kvJjHasAttrName(kvJjStrAttrs, name) {
			return &kvJjBound{obj: o, name: name}, nil
		}
		return kvJjUndef{name: name}, nil
	case []any, kvJjTuple:
		if kvJjHasAttrName(kvJjListAttrs, name) {
			return &kvJjBound{obj: o, name: name}, nil
		}
		return kvJjUndef{name: name}, nil
	case nil:
		return kvJjUndef{name: name}, nil
	}
	return nil, fmt.Errorf("attribute %q of %s is unsupported", name, kvJjTypeName(obj))
}

// kvJjGetItem is Jinja's sandboxed getitem: obj[key], falling back to the
// attribute for a string key, else Undefined. Only Undefined itself raises.
func kvJjGetItem(obj, key any) (any, error) {
	if u, ok := obj.(kvJjUndef); ok {
		return nil, fmt.Errorf("%q is undefined", u.name)
	}
	switch k := key.(type) {
	case string, kvJjMarkup:
		ks, _ := kvJjStr(k)
		if d, ok := obj.(*kvJjDict); ok {
			if v, ok := d.get(ks); ok {
				return v, nil
			}
		}
		if _, ok := obj.(*kvJjNS); ok {
			return nil, fmt.Errorf("namespace subscript is unsupported")
		}
		return kvJjGetAttr(obj, ks)
	case int, bool:
		i, _ := kvJjNum(k)
		var items []any
		switch o := obj.(type) {
		case []any:
			items = o
		case kvJjTuple:
			items = o
		case string, kvJjMarkup:
			s, _ := kvJjStr(o)
			rs := []rune(s)
			if i < 0 {
				i += len(rs)
			}
			if i < 0 || i >= len(rs) {
				return kvJjUndef{name: "index"}, nil
			}
			return string(rs[i]), nil
		case *kvJjDict, nil:
			return kvJjUndef{name: "index"}, nil
		default:
			return nil, fmt.Errorf("cannot index %s", kvJjTypeName(obj))
		}
		if i < 0 {
			i += len(items)
		}
		if i < 0 || i >= len(items) {
			return kvJjUndef{name: "index"}, nil
		}
		return items[i], nil
	}
	return nil, fmt.Errorf("subscript of type %s is unsupported", kvJjTypeName(key))
}

func (e *kvJjIndex) eval(rt *kvJjRT) (any, error) {
	obj, err := e.obj.eval(rt)
	if err != nil {
		return nil, err
	}
	idx, err := e.idx.eval(rt)
	if err != nil {
		return nil, err
	}
	v, err := kvJjGetItem(obj, idx)
	return v, kvJjAt(e.pos, err)
}

func (e *kvJjSlice) eval(rt *kvJjRT) (any, error) {
	obj, err := e.obj.eval(rt)
	if err != nil {
		return nil, err
	}
	var items []any
	var runes []rune
	str, tuple := false, false
	switch o := obj.(type) {
	case []any:
		items = o
	case kvJjTuple:
		items, tuple = o, true
	case string, kvJjMarkup:
		s, _ := kvJjStr(o)
		runes, str = []rune(s), true
	case kvJjUndef:
		return nil, kvJjErrf(e.pos, "%q is undefined", o.name)
	case nil, int, bool, *kvJjDict:
		return kvJjUndef{name: "slice"}, nil
	default:
		return nil, kvJjErrf(e.pos, "cannot slice %s", kvJjTypeName(obj))
	}
	n := len(items)
	if str {
		n = len(runes)
	}
	evalPart := func(part kvJjExpr) (int, bool, error) {
		if part == nil {
			return 0, false, nil
		}
		v, err := part.eval(rt)
		if err != nil {
			return 0, false, err
		}
		if v == nil {
			return 0, false, nil
		}
		i, ok := kvJjNum(v)
		if !ok {
			return 0, false, kvJjErrf(e.pos, "slice bound of type %s", kvJjTypeName(v))
		}
		return i, true, nil
	}
	step, hasStep, err := evalPart(e.step)
	if err != nil {
		return nil, err
	}
	if !hasStep {
		step = 1
	}
	if step == 0 {
		return nil, kvJjErrf(e.pos, "slice step cannot be zero")
	}
	start, hasStart, err := evalPart(e.start)
	if err != nil {
		return nil, err
	}
	stop, hasStop, err := evalPart(e.stop)
	if err != nil {
		return nil, err
	}
	clamp := func(i, lo, hi int) int {
		if i < lo {
			return lo
		}
		if i > hi {
			return hi
		}
		return i
	}
	var idxs []int
	if step > 0 {
		if !hasStart {
			start = 0
		} else if start < 0 {
			start += n
		}
		if !hasStop {
			stop = n
		} else if stop < 0 {
			stop += n
		}
		start, stop = clamp(start, 0, n), clamp(stop, 0, n)
		for i := start; i < stop; i += step {
			idxs = append(idxs, i)
		}
	} else {
		if !hasStart {
			start = n - 1
		} else if start < 0 {
			start += n
		}
		if !hasStop {
			stop = -1
		} else {
			if stop < 0 {
				stop += n
			}
			stop = clamp(stop, -1, n-1)
		}
		start = clamp(start, -1, n-1)
		for i := start; i > stop; i += step {
			idxs = append(idxs, i)
		}
	}
	if str {
		out := make([]rune, len(idxs))
		for k, i := range idxs {
			out[k] = runes[i]
		}
		return string(out), nil
	}
	out := make([]any, len(idxs))
	for k, i := range idxs {
		out[k] = items[i]
	}
	if tuple {
		return kvJjTuple(out), nil
	}
	return out, nil
}

func (a *kvJjCallArgs) eval(rt *kvJjRT) (*kvJjArgs, error) {
	out := &kvJjArgs{}
	if a == nil {
		return out, nil
	}
	for _, e := range a.pos {
		v, err := e.eval(rt)
		if err != nil {
			return nil, err
		}
		out.pos = append(out.pos, v)
	}
	for i, e := range a.kwVals {
		v, err := e.eval(rt)
		if err != nil {
			return nil, err
		}
		out.kw = append(out.kw, kvJjKw{name: a.kw[i], val: v})
	}
	return out, nil
}

func (e *kvJjCall) eval(rt *kvJjRT) (any, error) {
	// obj.method(...) dispatches on the receiver directly.
	if at, ok := e.fn.(*kvJjAttr); ok {
		obj, err := at.obj.eval(rt)
		if err != nil {
			return nil, err
		}
		args, err := e.args.eval(rt)
		if err != nil {
			return nil, err
		}
		if ns, ok := obj.(*kvJjNS); ok {
			fn, _ := kvJjGetAttr(ns, at.name)
			return kvJjCallValue(rt, fn, args, e.pos)
		}
		v, err := kvJjCallMethod(obj, at.name, args)
		return v, kvJjAt(at.pos, err)
	}
	fn, err := e.fn.eval(rt)
	if err != nil {
		return nil, err
	}
	args, err := e.args.eval(rt)
	if err != nil {
		return nil, err
	}
	return kvJjCallValue(rt, fn, args, e.pos)
}

func kvJjCallValue(rt *kvJjRT, fn any, args *kvJjArgs, pos int) (any, error) {
	switch f := fn.(type) {
	case *kvJjMacro:
		return f.call(rt, args)
	case *kvJjBuiltin:
		v, err := f.fn(rt, args)
		return v, kvJjAt(pos, err)
	case *kvJjBound:
		v, err := kvJjCallMethod(f.obj, f.name, args)
		return v, kvJjAt(pos, err)
	case kvJjUndef:
		return nil, kvJjErrf(pos, "%q is undefined", f.name)
	}
	return nil, kvJjErrf(pos, "%s object is not callable", kvJjTypeName(fn))
}

func (e *kvJjFilter) eval(rt *kvJjRT) (any, error) {
	v, err := e.e.eval(rt)
	if err != nil {
		return nil, err
	}
	args, err := e.args.eval(rt)
	if err != nil {
		return nil, err
	}
	f := kvJjFilters[e.name]
	out, err := f(rt, v, args)
	return out, kvJjAt(e.pos, err)
}

func (e *kvJjTest) eval(rt *kvJjRT) (any, error) {
	v, err := e.e.eval(rt)
	if err != nil {
		return nil, err
	}
	args := make([]any, len(e.args))
	for i, a := range e.args {
		if args[i], err = a.eval(rt); err != nil {
			return nil, err
		}
	}
	res, err := kvJjRunTest(e.name, v, args)
	if err != nil {
		return nil, kvJjAt(e.pos, err)
	}
	if e.negate {
		res = !res
	}
	return res, nil
}
