// SPDX-License-Identifier: Apache-2.0
//
// ai_kv_jinja_construct_test.go — per-construct executor parity against the
// HF chat-template environment.
//
// cicd/common/kv_hash/fixtures/kv_jinja_construct_parity.json is generated by
// gen_jinja_construct_fixtures.py inside the engine image, so every row's
// expectation comes from jinja2 + transformers themselves. A row either
// renders (the executor must produce the same bytes, or refuse it and be
// listed in kvJjConstructRefused with the reason) or raises (the executor
// must fail too — a refusal is never allowed to turn into output).

package loxinet

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"testing"
	"time"
)

// kvJjConstructRefused lists oracle rows that render in Jinja but that the
// executor deliberately refuses. A refusal faults the render (safe); it is
// listed so the subset's edge is explicit and a row that starts passing
// fails the test until it is removed from here.
var kvJjConstructRefused = map[string]string{
	"cmp-chained":       "chained comparisons are not implemented",
	"arith-div-float":   "true division yields a float",
	"method-str-format": "str.format is not implemented",
	"cycler-refused":    "cycler global is not implemented",
	"repr-namespace":    "Namespace repr is not implemented",
	"safe-concat-plus":  "Markup + str HTML-escapes the plain operand",
	"ws-raw-block":      "raw blocks are not implemented",
	"filter-int":        "int filter is not implemented",
}

type kvJjConstructRow struct {
	Name     string          `json:"name"`
	Template string          `json:"template"`
	Context  json.RawMessage `json:"context"`
	Rendered *string         `json:"rendered"`
	Error    string          `json:"error"`
}

// kvJjDecodeOrdered decodes JSON into the executor's value model, keeping
// object key order (Python dicts in the oracle's context are ordered).
func kvJjDecodeOrdered(dec *json.Decoder) (any, error) {
	tok, err := dec.Token()
	if err != nil {
		return nil, err
	}
	switch t := tok.(type) {
	case json.Delim:
		switch t {
		case '{':
			d := kvJjNewDict()
			for dec.More() {
				kt, err := dec.Token()
				if err != nil {
					return nil, err
				}
				v, err := kvJjDecodeOrdered(dec)
				if err != nil {
					return nil, err
				}
				d.set(kt.(string), v)
			}
			_, err := dec.Token()
			return d, err
		case '[':
			out := []any{}
			for dec.More() {
				v, err := kvJjDecodeOrdered(dec)
				if err != nil {
					return nil, err
				}
				out = append(out, v)
			}
			_, err := dec.Token()
			return out, err
		}
	case json.Number:
		n, err := t.Int64()
		if err != nil {
			return nil, fmt.Errorf("non-integer number %s", t)
		}
		return int(n), nil
	case string, bool, nil:
		return t, nil
	}
	return nil, fmt.Errorf("unexpected token %v", tok)
}

func kvJjDecodeContext(raw json.RawMessage) (map[string]any, error) {
	dec := json.NewDecoder(bytes.NewReader(raw))
	dec.UseNumber()
	v, err := kvJjDecodeOrdered(dec)
	if err != nil {
		return nil, err
	}
	if _, err := dec.Token(); err != io.EOF {
		return nil, fmt.Errorf("trailing data in context")
	}
	d, ok := v.(*kvJjDict)
	if !ok {
		return nil, fmt.Errorf("context is not an object")
	}
	ctx := map[string]any{}
	for _, k := range d.keys {
		ctx[k] = d.vals[k]
	}
	return ctx, nil
}

func TestKvJinjaConstructParity(t *testing.T) {
	data, err := os.ReadFile(kvHashFixturePath(t, "kv_jinja_construct_parity.json"))
	if err != nil {
		t.Fatalf("construct parity fixture missing: %v", err)
	}
	var f struct {
		FrozenNow string             `json:"frozen_now"`
		Cases     []kvJjConstructRow `json:"cases"`
	}
	if err := json.Unmarshal(data, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	if len(f.Cases) < 150 {
		t.Fatalf("fixture has %d rows; the oracle battery shrank", len(f.Cases))
	}
	frozen, err := time.Parse("2006-01-02T15:04:05", f.FrozenNow)
	if err != nil {
		t.Fatalf("frozen_now: %v", err)
	}
	seen := map[string]bool{}
	var refusedOK, matched, raised int
	for _, row := range f.Cases {
		row := row
		seen[row.Name] = true
		t.Run(row.Name, func(t *testing.T) {
			ctx, err := kvJjDecodeContext(row.Context)
			if err != nil {
				t.Fatalf("context: %v", err)
			}
			ctx["strftime_now"] = kvJjStrftimeNow(func() time.Time { return frozen })
			var got string
			tpl, gerr := kvJinjaCompile(row.Template)
			if gerr == nil {
				got, gerr = tpl.Render(ctx)
			}
			reason, refused := kvJjConstructRefused[row.Name]
			switch {
			case row.Rendered == nil:
				raised++
				if gerr == nil {
					t.Fatalf("Jinja raises (%s) but the executor rendered %q", row.Error, got)
				}
			case gerr != nil:
				if !refused {
					t.Fatalf("executor failed on a row Jinja renders as %q: %v", *row.Rendered, gerr)
				}
				refusedOK++
				t.Logf("refused (%s): %v", reason, gerr)
			default:
				if got != *row.Rendered {
					t.Fatalf("render mismatch:\n got:  %q\n want: %q", got, *row.Rendered)
				}
				if refused {
					t.Fatalf("row renders correctly now; remove it from kvJjConstructRefused")
				}
				matched++
			}
		})
	}
	for name := range kvJjConstructRefused {
		if !seen[name] {
			t.Errorf("kvJjConstructRefused names %q, which is not an oracle row", name)
		}
	}
	t.Logf("construct parity: %d byte-identical, %d raise in both, %d refused", matched, raised, refusedOK)
}
