#!/usr/bin/env python3
"""Generate whole-template goldens for CANDIDATE models (kv_chat_render_candidates.json).

gen_chat_render_fixtures.py banks goldens for the models whose templates are
already served by profiles. Before a model can get a profile, the executor
must reproduce its template byte-for-byte; this generator produces that
evidence for templates that are only pinned so far. Each entry carries the
template source itself (the pinned bytes, digest-checked against pins.json),
so the goldens are self-contained and the Go test needs no banked artifact.

Rendering goes through tokenizer.apply_chat_template with the pinned template
passed explicitly, exactly as the engine calls it: the special-token strings
are passed as template variables, tools/documents are None, and
add_generation_prompt is True. strftime_now is frozen (the Go test injects
the same instant under the declared clock policy). A case the template
refuses (raise_exception, unsupported role order) is recorded as an error:
the executor must refuse it too.

Usage (inside the engine image):
  gen_chat_render_candidates.py <out.json> <pins.json> <artifacts_dir> <slug>[,<slug>...]

<artifacts_dir>/<slug>/ holds _effective_template.jinja plus the pinned
tokenizer files.
"""
import datetime as _dt
import hashlib
import json
import os
import sys

from gen_chat_render_fixtures import CASES as BANKED_CASES

FROZEN_NOW = _dt.datetime(2026, 3, 5, 7, 8, 9)

# The banked battery plus cases that exercise what the newer templates branch
# on: a conversation ending on an assistant turn, a system message out of
# place, a tool-role turn (a request may carry one without declaring tools),
# and a multi-part-free system-only prompt.
CASES = dict(BANKED_CASES)
CASES.update({
    "assistant-last": [
        {"role": "user", "content": "Hi"},
        {"role": "assistant", "content": "Hello! How can I help?"},
    ],
    "system-mid": [
        {"role": "user", "content": "One"},
        {"role": "system", "content": "Late system."},
        {"role": "user", "content": "Two"},
    ],
    "tool-role": [
        {"role": "user", "content": "Weather in Seoul?"},
        {"role": "assistant", "content": "Checking."},
        {"role": "tool", "content": "{\"temp\": 21}"},
        {"role": "user", "content": "Thanks"},
    ],
    "system-only": [
        {"role": "system", "content": "You are a helpful assistant."},
    ],
})


def sha256_hex(b: bytes) -> str:
    return hashlib.sha256(b).hexdigest()


def main() -> int:
    if len(sys.argv) != 5:
        print(__doc__, file=sys.stderr)
        return 2
    out, pins_path, art, slugs = sys.argv[1:]
    import jinja2
    import transformers
    from transformers import AutoTokenizer
    from transformers.utils import chat_template_utils as ctu

    class _Frozen(_dt.datetime):
        @classmethod
        def now(cls, tz=None):
            return FROZEN_NOW

    ctu.datetime = _Frozen

    pins = json.load(open(pins_path))
    doc = {
        "_note": (
            "Candidate-model chat-template goldens generated by "
            "gen_chat_render_candidates.py through apply_chat_template in the "
            "engine image. `template` is the pinned source; a case with "
            "`error` is one the template itself refuses."
        ),
        "transformers_version": transformers.__version__,
        "jinja2_version": jinja2.__version__,
        "frozen_now": FROZEN_NOW.isoformat(),
        "models": {},
    }
    rc = 0
    for slug in slugs.split(","):
        pin = pins[slug]
        src_bytes = open(os.path.join(art, slug, "_effective_template.jinja"), "rb").read()
        sha = sha256_hex(src_bytes)
        if sha != pin["template_sha256"]:
            print(f"{slug}: template sha {sha} != pinned {pin['template_sha256']}", file=sys.stderr)
            return 1
        src = src_bytes.decode("utf-8")
        entry = {
            "model": pin["model"],
            "revision": pin["revision"],
            "template_sha256": sha,
            "template": src,
            "bos_token": pin.get("bos_token"),
            "eos_token": pin.get("eos_token"),
            "cases": {},
        }
        tok = None
        try:
            tok = AutoTokenizer.from_pretrained(os.path.join(art, slug), trust_remote_code=False)
            entry["special_tokens"] = {k: v for k, v in tok.special_tokens_map.items() if isinstance(v, str)}
            if tok.bos_token != pin.get("bos_token") or tok.eos_token != pin.get("eos_token"):
                print(f"{slug}: tokenizer bos/eos {tok.bos_token!r}/{tok.eos_token!r} disagree with pins", file=sys.stderr)
                return 1
        except Exception as e:  # noqa: BLE001 — recorded; render-only goldens
            entry["tokenizer_error"] = f"{type(e).__name__}: {e}"
            entry["special_tokens"] = {
                k: pin[k] for k in ("bos_token", "eos_token") if pin.get(k) is not None
            }
        for name, msgs in CASES.items():
            case = {"messages": msgs}
            try:
                if tok is not None:
                    rendered = tok.apply_chat_template(
                        msgs, chat_template=src, tokenize=False, add_generation_prompt=True
                    )
                else:
                    rendered = ctu.render_jinja_template(
                        conversations=[msgs], chat_template=src,
                        add_generation_prompt=True, **entry["special_tokens"],
                    )[0][0]
                case["rendered"] = rendered
                case["rendered_sha256"] = sha256_hex(rendered.encode("utf-8"))
                if tok is not None:
                    ids = tok.apply_chat_template(
                        msgs, chat_template=src, tokenize=True, add_generation_prompt=True
                    )
                    if not isinstance(ids, list):
                        ids = list(ids["input_ids"])
                    if ids and isinstance(ids[0], list):
                        ids = ids[0]
                    case["templated_ids"] = ids
                    case["encode_rendered_matches_templated"] = (
                        tok.encode(rendered, add_special_tokens=False) == ids
                    )
            except Exception as e:  # noqa: BLE001 — the refusal IS the golden
                case["error"] = f"{type(e).__name__}: {e}"
            entry["cases"][name] = case
        doc["models"][slug] = entry
        errs = sum(1 for c in entry["cases"].values() if "error" in c)
        tk = "tokenizer" if tok is not None else "NO-TOKENIZER"
        print(f"{slug}: {len(CASES)} cases, {errs} refused, {tk}, template {sha[:12]}")
    with open(out, "w") as f:
        json.dump(doc, f, ensure_ascii=False, indent=1)
        f.write("\n")
    return rc


if __name__ == "__main__":
    sys.exit(main())
