// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// DeleteAuditSinksNameNoContentCode is the HTTP code returned for type DeleteAuditSinksNameNoContent
const DeleteAuditSinksNameNoContentCode int = 204

/*
DeleteAuditSinksNameNoContent OK

swagger:response deleteAuditSinksNameNoContent
*/
type DeleteAuditSinksNameNoContent struct {
}

// NewDeleteAuditSinksNameNoContent creates DeleteAuditSinksNameNoContent with default headers values
func NewDeleteAuditSinksNameNoContent() *DeleteAuditSinksNameNoContent {

	return &DeleteAuditSinksNameNoContent{}
}

// WriteResponse to the client
func (o *DeleteAuditSinksNameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeleteAuditSinksNameUnauthorizedCode is the HTTP code returned for type DeleteAuditSinksNameUnauthorized
const DeleteAuditSinksNameUnauthorizedCode int = 401

/*
DeleteAuditSinksNameUnauthorized Missing or invalid management credential

swagger:response deleteAuditSinksNameUnauthorized
*/
type DeleteAuditSinksNameUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteAuditSinksNameUnauthorized creates DeleteAuditSinksNameUnauthorized with default headers values
func NewDeleteAuditSinksNameUnauthorized() *DeleteAuditSinksNameUnauthorized {

	return &DeleteAuditSinksNameUnauthorized{}
}

// WithPayload adds the payload to the delete audit sinks name unauthorized response
func (o *DeleteAuditSinksNameUnauthorized) WithPayload(payload *models.Error) *DeleteAuditSinksNameUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete audit sinks name unauthorized response
func (o *DeleteAuditSinksNameUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAuditSinksNameUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAuditSinksNameForbiddenCode is the HTTP code returned for type DeleteAuditSinksNameForbidden
const DeleteAuditSinksNameForbiddenCode int = 403

/*
DeleteAuditSinksNameForbidden Authenticated principal is not authorized for this operation

swagger:response deleteAuditSinksNameForbidden
*/
type DeleteAuditSinksNameForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteAuditSinksNameForbidden creates DeleteAuditSinksNameForbidden with default headers values
func NewDeleteAuditSinksNameForbidden() *DeleteAuditSinksNameForbidden {

	return &DeleteAuditSinksNameForbidden{}
}

// WithPayload adds the payload to the delete audit sinks name forbidden response
func (o *DeleteAuditSinksNameForbidden) WithPayload(payload *models.Error) *DeleteAuditSinksNameForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete audit sinks name forbidden response
func (o *DeleteAuditSinksNameForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAuditSinksNameForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAuditSinksNameNotFoundCode is the HTTP code returned for type DeleteAuditSinksNameNotFound
const DeleteAuditSinksNameNotFoundCode int = 404

/*
DeleteAuditSinksNameNotFound No sink of that name

swagger:response deleteAuditSinksNameNotFound
*/
type DeleteAuditSinksNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteAuditSinksNameNotFound creates DeleteAuditSinksNameNotFound with default headers values
func NewDeleteAuditSinksNameNotFound() *DeleteAuditSinksNameNotFound {

	return &DeleteAuditSinksNameNotFound{}
}

// WithPayload adds the payload to the delete audit sinks name not found response
func (o *DeleteAuditSinksNameNotFound) WithPayload(payload *models.Error) *DeleteAuditSinksNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete audit sinks name not found response
func (o *DeleteAuditSinksNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAuditSinksNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// DeleteAuditSinksNameServiceUnavailableCode is the HTTP code returned for type DeleteAuditSinksNameServiceUnavailable
const DeleteAuditSinksNameServiceUnavailableCode int = 503

/*
DeleteAuditSinksNameServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response deleteAuditSinksNameServiceUnavailable
*/
type DeleteAuditSinksNameServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewDeleteAuditSinksNameServiceUnavailable creates DeleteAuditSinksNameServiceUnavailable with default headers values
func NewDeleteAuditSinksNameServiceUnavailable() *DeleteAuditSinksNameServiceUnavailable {

	return &DeleteAuditSinksNameServiceUnavailable{}
}

// WithPayload adds the payload to the delete audit sinks name service unavailable response
func (o *DeleteAuditSinksNameServiceUnavailable) WithPayload(payload *models.Error) *DeleteAuditSinksNameServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete audit sinks name service unavailable response
func (o *DeleteAuditSinksNameServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteAuditSinksNameServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
