// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// DeleteAuditSinksNameHandlerFunc turns a function with the right signature into a delete audit sinks name handler
type DeleteAuditSinksNameHandlerFunc func(DeleteAuditSinksNameParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn DeleteAuditSinksNameHandlerFunc) Handle(params DeleteAuditSinksNameParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// DeleteAuditSinksNameHandler interface for that can handle valid delete audit sinks name params
type DeleteAuditSinksNameHandler interface {
	Handle(DeleteAuditSinksNameParams, interface{}) middleware.Responder
}

// NewDeleteAuditSinksName creates a new http.Handler for the delete audit sinks name operation
func NewDeleteAuditSinksName(ctx *middleware.Context, handler DeleteAuditSinksNameHandler) *DeleteAuditSinksName {
	return &DeleteAuditSinksName{Context: ctx, Handler: handler}
}

/*
	DeleteAuditSinksName swagger:route DELETE /audit/sinks/{name} audit deleteAuditSinksName

# Remove a secondary audit sink

Stops the sink. Its place in the trail and its export sequence are kept, so a sink configured under the same name afterwards continues both and no export sequence number is used twice. The change is audited like any other management mutation.
*/
type DeleteAuditSinksName struct {
	Context *middleware.Context
	Handler DeleteAuditSinksNameHandler
}

func (o *DeleteAuditSinksName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewDeleteAuditSinksNameParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
