// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuditSinksNameHandlerFunc turns a function with the right signature into a get audit sinks name handler
type GetAuditSinksNameHandlerFunc func(GetAuditSinksNameParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuditSinksNameHandlerFunc) Handle(params GetAuditSinksNameParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAuditSinksNameHandler interface for that can handle valid get audit sinks name params
type GetAuditSinksNameHandler interface {
	Handle(GetAuditSinksNameParams, interface{}) middleware.Responder
}

// NewGetAuditSinksName creates a new http.Handler for the get audit sinks name operation
func NewGetAuditSinksName(ctx *middleware.Context, handler GetAuditSinksNameHandler) *GetAuditSinksName {
	return &GetAuditSinksName{Context: ctx, Handler: handler}
}

/*
	GetAuditSinksName swagger:route GET /audit/sinks/{name} audit getAuditSinksName

# A secondary audit sink's configuration and state

Returns one secondary sink: where it sends, what it selects from the trail, and how far it has got. Certificate material is named by path and never served.
*/
type GetAuditSinksName struct {
	Context *middleware.Context
	Handler GetAuditSinksNameHandler
}

func (o *GetAuditSinksName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuditSinksNameParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
