// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuditPolicyHandlerFunc turns a function with the right signature into a get audit policy handler
type GetAuditPolicyHandlerFunc func(GetAuditPolicyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuditPolicyHandlerFunc) Handle(params GetAuditPolicyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAuditPolicyHandler interface for that can handle valid get audit policy params
type GetAuditPolicyHandler interface {
	Handle(GetAuditPolicyParams, interface{}) middleware.Responder
}

// NewGetAuditPolicy creates a new http.Handler for the get audit policy operation
func NewGetAuditPolicy(ctx *middleware.Context, handler GetAuditPolicyHandler) *GetAuditPolicy {
	return &GetAuditPolicy{Context: ctx, Handler: handler}
}

/*
	GetAuditPolicy swagger:route GET /audit/policy audit getAuditPolicy

# Audit policy in force

Returns the runtime-changeable part of the audit configuration: the limits that seal the active segment and the local retention target. The audit root directory, the mandatory-audit mode and the instance identity are startup-only and are not served here, because changing where the trail is written while it is being written would break the one thing the trail is for. This read is not itself audited, by the same decision that leaves the status read unaudited.
*/
type GetAuditPolicy struct {
	Context *middleware.Context
	Handler GetAuditPolicyHandler
}

func (o *GetAuditPolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuditPolicyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
