// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetAuditSinkHandlerFunc turns a function with the right signature into a get audit sink handler
type GetAuditSinkHandlerFunc func(GetAuditSinkParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAuditSinkHandlerFunc) Handle(params GetAuditSinkParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetAuditSinkHandler interface for that can handle valid get audit sink params
type GetAuditSinkHandler interface {
	Handle(GetAuditSinkParams, interface{}) middleware.Responder
}

// NewGetAuditSink creates a new http.Handler for the get audit sink operation
func NewGetAuditSink(ctx *middleware.Context, handler GetAuditSinkHandler) *GetAuditSink {
	return &GetAuditSink{Context: ctx, Handler: handler}
}

/*
	GetAuditSink swagger:route GET /audit/sink audit getAuditSink

# Audit sink configuration and state

Returns the remote sink's configuration and what is known about its current session. Certificate material is named by path and never served: the management API reports where the trust anchors are, not what they contain.
*/
type GetAuditSink struct {
	Context *middleware.Context
	Handler GetAuditSinkHandler
}

func (o *GetAuditSink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetAuditSinkParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
