// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetAuditPolicyOKCode is the HTTP code returned for type GetAuditPolicyOK
const GetAuditPolicyOKCode int = 200

/*
GetAuditPolicyOK Audit policy

swagger:response getAuditPolicyOK
*/
type GetAuditPolicyOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuditPolicy `json:"body,omitempty"`
}

// NewGetAuditPolicyOK creates GetAuditPolicyOK with default headers values
func NewGetAuditPolicyOK() *GetAuditPolicyOK {

	return &GetAuditPolicyOK{}
}

// WithPayload adds the payload to the get audit policy o k response
func (o *GetAuditPolicyOK) WithPayload(payload *models.AuditPolicy) *GetAuditPolicyOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit policy o k response
func (o *GetAuditPolicyOK) SetPayload(payload *models.AuditPolicy) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditPolicyOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditPolicyUnauthorizedCode is the HTTP code returned for type GetAuditPolicyUnauthorized
const GetAuditPolicyUnauthorizedCode int = 401

/*
GetAuditPolicyUnauthorized Missing or invalid management credential

swagger:response getAuditPolicyUnauthorized
*/
type GetAuditPolicyUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditPolicyUnauthorized creates GetAuditPolicyUnauthorized with default headers values
func NewGetAuditPolicyUnauthorized() *GetAuditPolicyUnauthorized {

	return &GetAuditPolicyUnauthorized{}
}

// WithPayload adds the payload to the get audit policy unauthorized response
func (o *GetAuditPolicyUnauthorized) WithPayload(payload *models.Error) *GetAuditPolicyUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit policy unauthorized response
func (o *GetAuditPolicyUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditPolicyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditPolicyForbiddenCode is the HTTP code returned for type GetAuditPolicyForbidden
const GetAuditPolicyForbiddenCode int = 403

/*
GetAuditPolicyForbidden Authenticated principal is not authorized for this operation

swagger:response getAuditPolicyForbidden
*/
type GetAuditPolicyForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditPolicyForbidden creates GetAuditPolicyForbidden with default headers values
func NewGetAuditPolicyForbidden() *GetAuditPolicyForbidden {

	return &GetAuditPolicyForbidden{}
}

// WithPayload adds the payload to the get audit policy forbidden response
func (o *GetAuditPolicyForbidden) WithPayload(payload *models.Error) *GetAuditPolicyForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit policy forbidden response
func (o *GetAuditPolicyForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditPolicyForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditPolicyServiceUnavailableCode is the HTTP code returned for type GetAuditPolicyServiceUnavailable
const GetAuditPolicyServiceUnavailableCode int = 503

/*
GetAuditPolicyServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getAuditPolicyServiceUnavailable
*/
type GetAuditPolicyServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditPolicyServiceUnavailable creates GetAuditPolicyServiceUnavailable with default headers values
func NewGetAuditPolicyServiceUnavailable() *GetAuditPolicyServiceUnavailable {

	return &GetAuditPolicyServiceUnavailable{}
}

// WithPayload adds the payload to the get audit policy service unavailable response
func (o *GetAuditPolicyServiceUnavailable) WithPayload(payload *models.Error) *GetAuditPolicyServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit policy service unavailable response
func (o *GetAuditPolicyServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditPolicyServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
