// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetAuditSinksNameOKCode is the HTTP code returned for type GetAuditSinksNameOK
const GetAuditSinksNameOKCode int = 200

/*
GetAuditSinksNameOK Audit sink

swagger:response getAuditSinksNameOK
*/
type GetAuditSinksNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuditNamedSink `json:"body,omitempty"`
}

// NewGetAuditSinksNameOK creates GetAuditSinksNameOK with default headers values
func NewGetAuditSinksNameOK() *GetAuditSinksNameOK {

	return &GetAuditSinksNameOK{}
}

// WithPayload adds the payload to the get audit sinks name o k response
func (o *GetAuditSinksNameOK) WithPayload(payload *models.AuditNamedSink) *GetAuditSinksNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sinks name o k response
func (o *GetAuditSinksNameOK) SetPayload(payload *models.AuditNamedSink) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinksNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditSinksNameUnauthorizedCode is the HTTP code returned for type GetAuditSinksNameUnauthorized
const GetAuditSinksNameUnauthorizedCode int = 401

/*
GetAuditSinksNameUnauthorized Missing or invalid management credential

swagger:response getAuditSinksNameUnauthorized
*/
type GetAuditSinksNameUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditSinksNameUnauthorized creates GetAuditSinksNameUnauthorized with default headers values
func NewGetAuditSinksNameUnauthorized() *GetAuditSinksNameUnauthorized {

	return &GetAuditSinksNameUnauthorized{}
}

// WithPayload adds the payload to the get audit sinks name unauthorized response
func (o *GetAuditSinksNameUnauthorized) WithPayload(payload *models.Error) *GetAuditSinksNameUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sinks name unauthorized response
func (o *GetAuditSinksNameUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinksNameUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditSinksNameForbiddenCode is the HTTP code returned for type GetAuditSinksNameForbidden
const GetAuditSinksNameForbiddenCode int = 403

/*
GetAuditSinksNameForbidden Authenticated principal is not authorized for this operation

swagger:response getAuditSinksNameForbidden
*/
type GetAuditSinksNameForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditSinksNameForbidden creates GetAuditSinksNameForbidden with default headers values
func NewGetAuditSinksNameForbidden() *GetAuditSinksNameForbidden {

	return &GetAuditSinksNameForbidden{}
}

// WithPayload adds the payload to the get audit sinks name forbidden response
func (o *GetAuditSinksNameForbidden) WithPayload(payload *models.Error) *GetAuditSinksNameForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sinks name forbidden response
func (o *GetAuditSinksNameForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinksNameForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditSinksNameNotFoundCode is the HTTP code returned for type GetAuditSinksNameNotFound
const GetAuditSinksNameNotFoundCode int = 404

/*
GetAuditSinksNameNotFound No sink of that name

swagger:response getAuditSinksNameNotFound
*/
type GetAuditSinksNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditSinksNameNotFound creates GetAuditSinksNameNotFound with default headers values
func NewGetAuditSinksNameNotFound() *GetAuditSinksNameNotFound {

	return &GetAuditSinksNameNotFound{}
}

// WithPayload adds the payload to the get audit sinks name not found response
func (o *GetAuditSinksNameNotFound) WithPayload(payload *models.Error) *GetAuditSinksNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sinks name not found response
func (o *GetAuditSinksNameNotFound) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinksNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditSinksNameServiceUnavailableCode is the HTTP code returned for type GetAuditSinksNameServiceUnavailable
const GetAuditSinksNameServiceUnavailableCode int = 503

/*
GetAuditSinksNameServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getAuditSinksNameServiceUnavailable
*/
type GetAuditSinksNameServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditSinksNameServiceUnavailable creates GetAuditSinksNameServiceUnavailable with default headers values
func NewGetAuditSinksNameServiceUnavailable() *GetAuditSinksNameServiceUnavailable {

	return &GetAuditSinksNameServiceUnavailable{}
}

// WithPayload adds the payload to the get audit sinks name service unavailable response
func (o *GetAuditSinksNameServiceUnavailable) WithPayload(payload *models.Error) *GetAuditSinksNameServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sinks name service unavailable response
func (o *GetAuditSinksNameServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinksNameServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
