// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetAuditSinkOKCode is the HTTP code returned for type GetAuditSinkOK
const GetAuditSinkOKCode int = 200

/*
GetAuditSinkOK Audit sink

swagger:response getAuditSinkOK
*/
type GetAuditSinkOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuditSink `json:"body,omitempty"`
}

// NewGetAuditSinkOK creates GetAuditSinkOK with default headers values
func NewGetAuditSinkOK() *GetAuditSinkOK {

	return &GetAuditSinkOK{}
}

// WithPayload adds the payload to the get audit sink o k response
func (o *GetAuditSinkOK) WithPayload(payload *models.AuditSink) *GetAuditSinkOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sink o k response
func (o *GetAuditSinkOK) SetPayload(payload *models.AuditSink) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinkOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditSinkUnauthorizedCode is the HTTP code returned for type GetAuditSinkUnauthorized
const GetAuditSinkUnauthorizedCode int = 401

/*
GetAuditSinkUnauthorized Missing or invalid management credential

swagger:response getAuditSinkUnauthorized
*/
type GetAuditSinkUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditSinkUnauthorized creates GetAuditSinkUnauthorized with default headers values
func NewGetAuditSinkUnauthorized() *GetAuditSinkUnauthorized {

	return &GetAuditSinkUnauthorized{}
}

// WithPayload adds the payload to the get audit sink unauthorized response
func (o *GetAuditSinkUnauthorized) WithPayload(payload *models.Error) *GetAuditSinkUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sink unauthorized response
func (o *GetAuditSinkUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinkUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditSinkForbiddenCode is the HTTP code returned for type GetAuditSinkForbidden
const GetAuditSinkForbiddenCode int = 403

/*
GetAuditSinkForbidden Authenticated principal is not authorized for this operation

swagger:response getAuditSinkForbidden
*/
type GetAuditSinkForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditSinkForbidden creates GetAuditSinkForbidden with default headers values
func NewGetAuditSinkForbidden() *GetAuditSinkForbidden {

	return &GetAuditSinkForbidden{}
}

// WithPayload adds the payload to the get audit sink forbidden response
func (o *GetAuditSinkForbidden) WithPayload(payload *models.Error) *GetAuditSinkForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sink forbidden response
func (o *GetAuditSinkForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinkForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuditSinkServiceUnavailableCode is the HTTP code returned for type GetAuditSinkServiceUnavailable
const GetAuditSinkServiceUnavailableCode int = 503

/*
GetAuditSinkServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getAuditSinkServiceUnavailable
*/
type GetAuditSinkServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetAuditSinkServiceUnavailable creates GetAuditSinkServiceUnavailable with default headers values
func NewGetAuditSinkServiceUnavailable() *GetAuditSinkServiceUnavailable {

	return &GetAuditSinkServiceUnavailable{}
}

// WithPayload adds the payload to the get audit sink service unavailable response
func (o *GetAuditSinkServiceUnavailable) WithPayload(payload *models.Error) *GetAuditSinkServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get audit sink service unavailable response
func (o *GetAuditSinkServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuditSinkServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
