// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAuditPolicyHandlerFunc turns a function with the right signature into a post audit policy handler
type PostAuditPolicyHandlerFunc func(PostAuditPolicyParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuditPolicyHandlerFunc) Handle(params PostAuditPolicyParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostAuditPolicyHandler interface for that can handle valid post audit policy params
type PostAuditPolicyHandler interface {
	Handle(PostAuditPolicyParams, interface{}) middleware.Responder
}

// NewPostAuditPolicy creates a new http.Handler for the post audit policy operation
func NewPostAuditPolicy(ctx *middleware.Context, handler PostAuditPolicyHandler) *PostAuditPolicy {
	return &PostAuditPolicy{Context: ctx, Handler: handler}
}

/*
	PostAuditPolicy swagger:route POST /audit/policy audit postAuditPolicy

# Change the audit policy

Replaces the runtime-changeable audit policy. The change is itself audited before it is applied, like any other management mutation. A value below the deployment profile's floor is refused for every caller, the gateway administrator included, and the refusal names the fields. That refusal answers 400, not 403: the caller was authorized and the values were not acceptable, and a 403 here would be recorded as an authorization denial rather than as the refused policy change it is. Lowering a retention target never deletes segments already on disk: they keep the terms they were sealed under, and only what is sealed afterwards is subject to the shorter one. The body replaces the whole policy: a field left out is set to its zero value, which for a retention limit means no limit, and is not kept from the policy before. The policy is held in memory only. It is not part of the persisted configuration document, unlike the sinks, and a restart brings back the values the gateway starts with: its startup segment limits and no retention limit. A deployment that needs a policy to hold across restarts applies the whole of it again after every start, and reads it back.
*/
type PostAuditPolicy struct {
	Context *middleware.Context
	Handler PostAuditPolicyHandler
}

func (o *PostAuditPolicy) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAuditPolicyParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
