// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostAuditRotateOKCode is the HTTP code returned for type PostAuditRotateOK
const PostAuditRotateOKCode int = 200

/*
PostAuditRotateOK Segment rotated

swagger:response postAuditRotateOK
*/
type PostAuditRotateOK struct {

	/*
	  In: Body
	*/
	Payload *models.AuditRotateResult `json:"body,omitempty"`
}

// NewPostAuditRotateOK creates PostAuditRotateOK with default headers values
func NewPostAuditRotateOK() *PostAuditRotateOK {

	return &PostAuditRotateOK{}
}

// WithPayload adds the payload to the post audit rotate o k response
func (o *PostAuditRotateOK) WithPayload(payload *models.AuditRotateResult) *PostAuditRotateOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit rotate o k response
func (o *PostAuditRotateOK) SetPayload(payload *models.AuditRotateResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditRotateOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditRotateUnauthorizedCode is the HTTP code returned for type PostAuditRotateUnauthorized
const PostAuditRotateUnauthorizedCode int = 401

/*
PostAuditRotateUnauthorized Missing or invalid management credential

swagger:response postAuditRotateUnauthorized
*/
type PostAuditRotateUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditRotateUnauthorized creates PostAuditRotateUnauthorized with default headers values
func NewPostAuditRotateUnauthorized() *PostAuditRotateUnauthorized {

	return &PostAuditRotateUnauthorized{}
}

// WithPayload adds the payload to the post audit rotate unauthorized response
func (o *PostAuditRotateUnauthorized) WithPayload(payload *models.Error) *PostAuditRotateUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit rotate unauthorized response
func (o *PostAuditRotateUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditRotateUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditRotateForbiddenCode is the HTTP code returned for type PostAuditRotateForbidden
const PostAuditRotateForbiddenCode int = 403

/*
PostAuditRotateForbidden Authenticated principal is not authorized for this operation

swagger:response postAuditRotateForbidden
*/
type PostAuditRotateForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditRotateForbidden creates PostAuditRotateForbidden with default headers values
func NewPostAuditRotateForbidden() *PostAuditRotateForbidden {

	return &PostAuditRotateForbidden{}
}

// WithPayload adds the payload to the post audit rotate forbidden response
func (o *PostAuditRotateForbidden) WithPayload(payload *models.Error) *PostAuditRotateForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit rotate forbidden response
func (o *PostAuditRotateForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditRotateForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditRotateServiceUnavailableCode is the HTTP code returned for type PostAuditRotateServiceUnavailable
const PostAuditRotateServiceUnavailableCode int = 503

/*
PostAuditRotateServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response postAuditRotateServiceUnavailable
*/
type PostAuditRotateServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditRotateServiceUnavailable creates PostAuditRotateServiceUnavailable with default headers values
func NewPostAuditRotateServiceUnavailable() *PostAuditRotateServiceUnavailable {

	return &PostAuditRotateServiceUnavailable{}
}

// WithPayload adds the payload to the post audit rotate service unavailable response
func (o *PostAuditRotateServiceUnavailable) WithPayload(payload *models.Error) *PostAuditRotateServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit rotate service unavailable response
func (o *PostAuditRotateServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditRotateServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
