// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAuditRotateHandlerFunc turns a function with the right signature into a post audit rotate handler
type PostAuditRotateHandlerFunc func(PostAuditRotateParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuditRotateHandlerFunc) Handle(params PostAuditRotateParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostAuditRotateHandler interface for that can handle valid post audit rotate params
type PostAuditRotateHandler interface {
	Handle(PostAuditRotateParams, interface{}) middleware.Responder
}

// NewPostAuditRotate creates a new http.Handler for the post audit rotate operation
func NewPostAuditRotate(ctx *middleware.Context, handler PostAuditRotateHandler) *PostAuditRotate {
	return &PostAuditRotate{Context: ctx, Handler: handler}
}

/*
	PostAuditRotate swagger:route POST /audit/rotate audit postAuditRotate

# Seal the active segment now

Seals the active segment and opens the next one, as the operator action of the same name. It is audited, and the record names both the segment that was sealed and the one now active.
*/
type PostAuditRotate struct {
	Context *middleware.Context
	Handler PostAuditRotateHandler
}

func (o *PostAuditRotate) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAuditRotateParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
