// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostAuditSinkHandlerFunc turns a function with the right signature into a post audit sink handler
type PostAuditSinkHandlerFunc func(PostAuditSinkParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostAuditSinkHandlerFunc) Handle(params PostAuditSinkParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostAuditSinkHandler interface for that can handle valid post audit sink params
type PostAuditSinkHandler interface {
	Handle(PostAuditSinkParams, interface{}) middleware.Responder
}

// NewPostAuditSink creates a new http.Handler for the post audit sink operation
func NewPostAuditSink(ctx *middleware.Context, handler PostAuditSinkHandler) *PostAuditSink {
	return &PostAuditSink{Context: ctx, Handler: handler}
}

/*
	PostAuditSink swagger:route POST /audit/sink audit postAuditSink

# Configure the audit sink

Configures the remote syslog sink. The receiver's certificate is always verified against the configured bundle; there is no mode that disables verification, and a configuration without a bundle is refused. The change is audited like any other management mutation. Syslog over TLS carries no acknowledgement from the receiver, so what the sink can know is what the receiver's transport has acknowledged. A record is behind the sink once it has been written to the session; records written and not yet acknowledged are remembered with the sink's place in the trail, and are sent again after the session fails and after a restart of the gateway, orderly or not. A receiver therefore sees a record at least once up to its own transport and may see it more than once, and removes repeats by (instance_id, boot_id, seq). What a receiver has acknowledged and then loses before storing it is covered only by the fixed number of records sent again after a session that failed, and not across a restart of the gateway.
*/
type PostAuditSink struct {
	Context *middleware.Context
	Handler PostAuditSinkHandler
}

func (o *PostAuditSink) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostAuditSinkParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
