// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostAuditSinkNoContentCode is the HTTP code returned for type PostAuditSinkNoContent
const PostAuditSinkNoContentCode int = 204

/*
PostAuditSinkNoContent OK

swagger:response postAuditSinkNoContent
*/
type PostAuditSinkNoContent struct {
}

// NewPostAuditSinkNoContent creates PostAuditSinkNoContent with default headers values
func NewPostAuditSinkNoContent() *PostAuditSinkNoContent {

	return &PostAuditSinkNoContent{}
}

// WriteResponse to the client
func (o *PostAuditSinkNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostAuditSinkBadRequestCode is the HTTP code returned for type PostAuditSinkBadRequest
const PostAuditSinkBadRequestCode int = 400

/*
PostAuditSinkBadRequest The request is malformed or the values are not acceptable; nothing was changed

swagger:response postAuditSinkBadRequest
*/
type PostAuditSinkBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditSinkBadRequest creates PostAuditSinkBadRequest with default headers values
func NewPostAuditSinkBadRequest() *PostAuditSinkBadRequest {

	return &PostAuditSinkBadRequest{}
}

// WithPayload adds the payload to the post audit sink bad request response
func (o *PostAuditSinkBadRequest) WithPayload(payload *models.Error) *PostAuditSinkBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit sink bad request response
func (o *PostAuditSinkBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditSinkBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditSinkUnauthorizedCode is the HTTP code returned for type PostAuditSinkUnauthorized
const PostAuditSinkUnauthorizedCode int = 401

/*
PostAuditSinkUnauthorized Missing or invalid management credential

swagger:response postAuditSinkUnauthorized
*/
type PostAuditSinkUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditSinkUnauthorized creates PostAuditSinkUnauthorized with default headers values
func NewPostAuditSinkUnauthorized() *PostAuditSinkUnauthorized {

	return &PostAuditSinkUnauthorized{}
}

// WithPayload adds the payload to the post audit sink unauthorized response
func (o *PostAuditSinkUnauthorized) WithPayload(payload *models.Error) *PostAuditSinkUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit sink unauthorized response
func (o *PostAuditSinkUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditSinkUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditSinkForbiddenCode is the HTTP code returned for type PostAuditSinkForbidden
const PostAuditSinkForbiddenCode int = 403

/*
PostAuditSinkForbidden Authenticated principal is not authorized for this operation

swagger:response postAuditSinkForbidden
*/
type PostAuditSinkForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditSinkForbidden creates PostAuditSinkForbidden with default headers values
func NewPostAuditSinkForbidden() *PostAuditSinkForbidden {

	return &PostAuditSinkForbidden{}
}

// WithPayload adds the payload to the post audit sink forbidden response
func (o *PostAuditSinkForbidden) WithPayload(payload *models.Error) *PostAuditSinkForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit sink forbidden response
func (o *PostAuditSinkForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditSinkForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditSinkServiceUnavailableCode is the HTTP code returned for type PostAuditSinkServiceUnavailable
const PostAuditSinkServiceUnavailableCode int = 503

/*
PostAuditSinkServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response postAuditSinkServiceUnavailable
*/
type PostAuditSinkServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditSinkServiceUnavailable creates PostAuditSinkServiceUnavailable with default headers values
func NewPostAuditSinkServiceUnavailable() *PostAuditSinkServiceUnavailable {

	return &PostAuditSinkServiceUnavailable{}
}

// WithPayload adds the payload to the post audit sink service unavailable response
func (o *PostAuditSinkServiceUnavailable) WithPayload(payload *models.Error) *PostAuditSinkServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit sink service unavailable response
func (o *PostAuditSinkServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditSinkServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
