// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostAuditPolicyNoContentCode is the HTTP code returned for type PostAuditPolicyNoContent
const PostAuditPolicyNoContentCode int = 204

/*
PostAuditPolicyNoContent OK

swagger:response postAuditPolicyNoContent
*/
type PostAuditPolicyNoContent struct {
}

// NewPostAuditPolicyNoContent creates PostAuditPolicyNoContent with default headers values
func NewPostAuditPolicyNoContent() *PostAuditPolicyNoContent {

	return &PostAuditPolicyNoContent{}
}

// WriteResponse to the client
func (o *PostAuditPolicyNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PostAuditPolicyBadRequestCode is the HTTP code returned for type PostAuditPolicyBadRequest
const PostAuditPolicyBadRequestCode int = 400

/*
PostAuditPolicyBadRequest The request is malformed or the values are not acceptable; nothing was changed

swagger:response postAuditPolicyBadRequest
*/
type PostAuditPolicyBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditPolicyBadRequest creates PostAuditPolicyBadRequest with default headers values
func NewPostAuditPolicyBadRequest() *PostAuditPolicyBadRequest {

	return &PostAuditPolicyBadRequest{}
}

// WithPayload adds the payload to the post audit policy bad request response
func (o *PostAuditPolicyBadRequest) WithPayload(payload *models.Error) *PostAuditPolicyBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit policy bad request response
func (o *PostAuditPolicyBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditPolicyBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditPolicyUnauthorizedCode is the HTTP code returned for type PostAuditPolicyUnauthorized
const PostAuditPolicyUnauthorizedCode int = 401

/*
PostAuditPolicyUnauthorized Missing or invalid management credential

swagger:response postAuditPolicyUnauthorized
*/
type PostAuditPolicyUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditPolicyUnauthorized creates PostAuditPolicyUnauthorized with default headers values
func NewPostAuditPolicyUnauthorized() *PostAuditPolicyUnauthorized {

	return &PostAuditPolicyUnauthorized{}
}

// WithPayload adds the payload to the post audit policy unauthorized response
func (o *PostAuditPolicyUnauthorized) WithPayload(payload *models.Error) *PostAuditPolicyUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit policy unauthorized response
func (o *PostAuditPolicyUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditPolicyUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditPolicyForbiddenCode is the HTTP code returned for type PostAuditPolicyForbidden
const PostAuditPolicyForbiddenCode int = 403

/*
PostAuditPolicyForbidden Authenticated principal is not authorized for this operation

swagger:response postAuditPolicyForbidden
*/
type PostAuditPolicyForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditPolicyForbidden creates PostAuditPolicyForbidden with default headers values
func NewPostAuditPolicyForbidden() *PostAuditPolicyForbidden {

	return &PostAuditPolicyForbidden{}
}

// WithPayload adds the payload to the post audit policy forbidden response
func (o *PostAuditPolicyForbidden) WithPayload(payload *models.Error) *PostAuditPolicyForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit policy forbidden response
func (o *PostAuditPolicyForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditPolicyForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostAuditPolicyServiceUnavailableCode is the HTTP code returned for type PostAuditPolicyServiceUnavailable
const PostAuditPolicyServiceUnavailableCode int = 503

/*
PostAuditPolicyServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response postAuditPolicyServiceUnavailable
*/
type PostAuditPolicyServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostAuditPolicyServiceUnavailable creates PostAuditPolicyServiceUnavailable with default headers values
func NewPostAuditPolicyServiceUnavailable() *PostAuditPolicyServiceUnavailable {

	return &PostAuditPolicyServiceUnavailable{}
}

// WithPayload adds the payload to the post audit policy service unavailable response
func (o *PostAuditPolicyServiceUnavailable) WithPayload(payload *models.Error) *PostAuditPolicyServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post audit policy service unavailable response
func (o *PostAuditPolicyServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostAuditPolicyServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
