// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PutAuditSinksNameHandlerFunc turns a function with the right signature into a put audit sinks name handler
type PutAuditSinksNameHandlerFunc func(PutAuditSinksNameParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PutAuditSinksNameHandlerFunc) Handle(params PutAuditSinksNameParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PutAuditSinksNameHandler interface for that can handle valid put audit sinks name params
type PutAuditSinksNameHandler interface {
	Handle(PutAuditSinksNameParams, interface{}) middleware.Responder
}

// NewPutAuditSinksName creates a new http.Handler for the put audit sinks name operation
func NewPutAuditSinksName(ctx *middleware.Context, handler PutAuditSinksNameHandler) *PutAuditSinksName {
	return &PutAuditSinksName{Context: ctx, Handler: handler}
}

/*
	PutAuditSinksName swagger:route PUT /audit/sinks/{name} audit putAuditSinksName

# Create or replace a secondary audit sink

Configures a secondary sink that follows the trail beside the compliance sink of /audit/sink. A secondary sink may select records by stream, service and outcome and may sample the data stream; it numbers what it sends, and that export sequence travels beside each record under the configured private enterprise number, so a configuration without one is refused. The receiver's certificate is always verified. Replacing a sink keeps its place in the trail and its export sequence. The name compliance is reserved. The change is audited like any other management mutation.
*/
type PutAuditSinksName struct {
	Context *middleware.Context
	Handler PutAuditSinksNameHandler
}

func (o *PutAuditSinksName) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPutAuditSinksNameParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
