// Code generated by go-swagger; DO NOT EDIT.

package audit

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PutAuditSinksNameNoContentCode is the HTTP code returned for type PutAuditSinksNameNoContent
const PutAuditSinksNameNoContentCode int = 204

/*
PutAuditSinksNameNoContent OK

swagger:response putAuditSinksNameNoContent
*/
type PutAuditSinksNameNoContent struct {
}

// NewPutAuditSinksNameNoContent creates PutAuditSinksNameNoContent with default headers values
func NewPutAuditSinksNameNoContent() *PutAuditSinksNameNoContent {

	return &PutAuditSinksNameNoContent{}
}

// WriteResponse to the client
func (o *PutAuditSinksNameNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// PutAuditSinksNameBadRequestCode is the HTTP code returned for type PutAuditSinksNameBadRequest
const PutAuditSinksNameBadRequestCode int = 400

/*
PutAuditSinksNameBadRequest The request is malformed or the values are not acceptable; nothing was changed

swagger:response putAuditSinksNameBadRequest
*/
type PutAuditSinksNameBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAuditSinksNameBadRequest creates PutAuditSinksNameBadRequest with default headers values
func NewPutAuditSinksNameBadRequest() *PutAuditSinksNameBadRequest {

	return &PutAuditSinksNameBadRequest{}
}

// WithPayload adds the payload to the put audit sinks name bad request response
func (o *PutAuditSinksNameBadRequest) WithPayload(payload *models.Error) *PutAuditSinksNameBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put audit sinks name bad request response
func (o *PutAuditSinksNameBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAuditSinksNameBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAuditSinksNameUnauthorizedCode is the HTTP code returned for type PutAuditSinksNameUnauthorized
const PutAuditSinksNameUnauthorizedCode int = 401

/*
PutAuditSinksNameUnauthorized Missing or invalid management credential

swagger:response putAuditSinksNameUnauthorized
*/
type PutAuditSinksNameUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAuditSinksNameUnauthorized creates PutAuditSinksNameUnauthorized with default headers values
func NewPutAuditSinksNameUnauthorized() *PutAuditSinksNameUnauthorized {

	return &PutAuditSinksNameUnauthorized{}
}

// WithPayload adds the payload to the put audit sinks name unauthorized response
func (o *PutAuditSinksNameUnauthorized) WithPayload(payload *models.Error) *PutAuditSinksNameUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put audit sinks name unauthorized response
func (o *PutAuditSinksNameUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAuditSinksNameUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAuditSinksNameForbiddenCode is the HTTP code returned for type PutAuditSinksNameForbidden
const PutAuditSinksNameForbiddenCode int = 403

/*
PutAuditSinksNameForbidden Authenticated principal is not authorized for this operation

swagger:response putAuditSinksNameForbidden
*/
type PutAuditSinksNameForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAuditSinksNameForbidden creates PutAuditSinksNameForbidden with default headers values
func NewPutAuditSinksNameForbidden() *PutAuditSinksNameForbidden {

	return &PutAuditSinksNameForbidden{}
}

// WithPayload adds the payload to the put audit sinks name forbidden response
func (o *PutAuditSinksNameForbidden) WithPayload(payload *models.Error) *PutAuditSinksNameForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put audit sinks name forbidden response
func (o *PutAuditSinksNameForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAuditSinksNameForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PutAuditSinksNameServiceUnavailableCode is the HTTP code returned for type PutAuditSinksNameServiceUnavailable
const PutAuditSinksNameServiceUnavailableCode int = 503

/*
PutAuditSinksNameServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response putAuditSinksNameServiceUnavailable
*/
type PutAuditSinksNameServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPutAuditSinksNameServiceUnavailable creates PutAuditSinksNameServiceUnavailable with default headers values
func NewPutAuditSinksNameServiceUnavailable() *PutAuditSinksNameServiceUnavailable {

	return &PutAuditSinksNameServiceUnavailable{}
}

// WithPayload adds the payload to the put audit sinks name service unavailable response
func (o *PutAuditSinksNameServiceUnavailable) WithPayload(payload *models.Error) *PutAuditSinksNameServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put audit sinks name service unavailable response
func (o *PutAuditSinksNameServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutAuditSinksNameServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
