// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// GetConfigHalfcloseOKCode is the HTTP code returned for type GetConfigHalfcloseOK
const GetConfigHalfcloseOKCode int = 200

/*
GetConfigHalfcloseOK OK

swagger:response getConfigHalfcloseOK
*/
type GetConfigHalfcloseOK struct {

	/*
	  In: Body
	*/
	Payload *models.HalfCloseConfig `json:"body,omitempty"`
}

// NewGetConfigHalfcloseOK creates GetConfigHalfcloseOK with default headers values
func NewGetConfigHalfcloseOK() *GetConfigHalfcloseOK {

	return &GetConfigHalfcloseOK{}
}

// WithPayload adds the payload to the get config halfclose o k response
func (o *GetConfigHalfcloseOK) WithPayload(payload *models.HalfCloseConfig) *GetConfigHalfcloseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config halfclose o k response
func (o *GetConfigHalfcloseOK) SetPayload(payload *models.HalfCloseConfig) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigHalfcloseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigHalfcloseUnauthorizedCode is the HTTP code returned for type GetConfigHalfcloseUnauthorized
const GetConfigHalfcloseUnauthorizedCode int = 401

/*
GetConfigHalfcloseUnauthorized Invalid authentication credentials

swagger:response getConfigHalfcloseUnauthorized
*/
type GetConfigHalfcloseUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigHalfcloseUnauthorized creates GetConfigHalfcloseUnauthorized with default headers values
func NewGetConfigHalfcloseUnauthorized() *GetConfigHalfcloseUnauthorized {

	return &GetConfigHalfcloseUnauthorized{}
}

// WithPayload adds the payload to the get config halfclose unauthorized response
func (o *GetConfigHalfcloseUnauthorized) WithPayload(payload *models.Error) *GetConfigHalfcloseUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config halfclose unauthorized response
func (o *GetConfigHalfcloseUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigHalfcloseUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigHalfcloseForbiddenCode is the HTTP code returned for type GetConfigHalfcloseForbidden
const GetConfigHalfcloseForbiddenCode int = 403

/*
GetConfigHalfcloseForbidden Authenticated principal is not authorized for this operation

swagger:response getConfigHalfcloseForbidden
*/
type GetConfigHalfcloseForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigHalfcloseForbidden creates GetConfigHalfcloseForbidden with default headers values
func NewGetConfigHalfcloseForbidden() *GetConfigHalfcloseForbidden {

	return &GetConfigHalfcloseForbidden{}
}

// WithPayload adds the payload to the get config halfclose forbidden response
func (o *GetConfigHalfcloseForbidden) WithPayload(payload *models.Error) *GetConfigHalfcloseForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config halfclose forbidden response
func (o *GetConfigHalfcloseForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigHalfcloseForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigHalfcloseInternalServerErrorCode is the HTTP code returned for type GetConfigHalfcloseInternalServerError
const GetConfigHalfcloseInternalServerErrorCode int = 500

/*
GetConfigHalfcloseInternalServerError Internal service error

swagger:response getConfigHalfcloseInternalServerError
*/
type GetConfigHalfcloseInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigHalfcloseInternalServerError creates GetConfigHalfcloseInternalServerError with default headers values
func NewGetConfigHalfcloseInternalServerError() *GetConfigHalfcloseInternalServerError {

	return &GetConfigHalfcloseInternalServerError{}
}

// WithPayload adds the payload to the get config halfclose internal server error response
func (o *GetConfigHalfcloseInternalServerError) WithPayload(payload *models.Error) *GetConfigHalfcloseInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config halfclose internal server error response
func (o *GetConfigHalfcloseInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigHalfcloseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetConfigHalfcloseServiceUnavailableCode is the HTTP code returned for type GetConfigHalfcloseServiceUnavailable
const GetConfigHalfcloseServiceUnavailableCode int = 503

/*
GetConfigHalfcloseServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response getConfigHalfcloseServiceUnavailable
*/
type GetConfigHalfcloseServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewGetConfigHalfcloseServiceUnavailable creates GetConfigHalfcloseServiceUnavailable with default headers values
func NewGetConfigHalfcloseServiceUnavailable() *GetConfigHalfcloseServiceUnavailable {

	return &GetConfigHalfcloseServiceUnavailable{}
}

// WithPayload adds the payload to the get config halfclose service unavailable response
func (o *GetConfigHalfcloseServiceUnavailable) WithPayload(payload *models.Error) *GetConfigHalfcloseServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get config halfclose service unavailable response
func (o *GetConfigHalfcloseServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetConfigHalfcloseServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
