// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetConfigHalfcloseHandlerFunc turns a function with the right signature into a get config halfclose handler
type GetConfigHalfcloseHandlerFunc func(GetConfigHalfcloseParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn GetConfigHalfcloseHandlerFunc) Handle(params GetConfigHalfcloseParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// GetConfigHalfcloseHandler interface for that can handle valid get config halfclose params
type GetConfigHalfcloseHandler interface {
	Handle(GetConfigHalfcloseParams, interface{}) middleware.Responder
}

// NewGetConfigHalfclose creates a new http.Handler for the get config halfclose operation
func NewGetConfigHalfclose(ctx *middleware.Context, handler GetConfigHalfcloseHandler) *GetConfigHalfclose {
	return &GetConfigHalfclose{Context: ctx, Handler: handler}
}

/*
	GetConfigHalfclose swagger:route GET /config/halfclose getConfigHalfclose

# Get the half-close hold settings

The process-wide settings for holding a client that half-closes after its request, on the services whose half_close_mode is hold: whether new holds may be taken, and the idle bound on a hold. Until they are set, the defaults are in force (allowed, 240 seconds) and are what this returns.
*/
type GetConfigHalfclose struct {
	Context *middleware.Context
	Handler GetConfigHalfcloseHandler
}

func (o *GetConfigHalfclose) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetConfigHalfcloseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
