// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigHalfcloseReleaseHandlerFunc turns a function with the right signature into a post config halfclose release handler
type PostConfigHalfcloseReleaseHandlerFunc func(PostConfigHalfcloseReleaseParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigHalfcloseReleaseHandlerFunc) Handle(params PostConfigHalfcloseReleaseParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigHalfcloseReleaseHandler interface for that can handle valid post config halfclose release params
type PostConfigHalfcloseReleaseHandler interface {
	Handle(PostConfigHalfcloseReleaseParams, interface{}) middleware.Responder
}

// NewPostConfigHalfcloseRelease creates a new http.Handler for the post config halfclose release operation
func NewPostConfigHalfcloseRelease(ctx *middleware.Context, handler PostConfigHalfcloseReleaseHandler) *PostConfigHalfcloseRelease {
	return &PostConfigHalfcloseRelease{Context: ctx, Handler: handler}
}

/*
	PostConfigHalfcloseRelease swagger:route POST /config/halfclose/release postConfigHalfcloseRelease

# Close every held half-closed client

Closes, at the data path's next pass (within a second), every client held after a half-close, on every service, as it would have been closed without the hold: both of its connections are shut and released. An answer still on its way to such a client is lost. Nothing is stored: holds taken afterwards are taken as before, so block new holds first (POST /config/halfclose with allow false) to stop them. Answers 200 whether or not anything is held.
*/
type PostConfigHalfcloseRelease struct {
	Context *middleware.Context
	Handler PostConfigHalfcloseReleaseHandler
}

func (o *PostConfigHalfcloseRelease) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigHalfcloseReleaseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
