// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigHalfcloseReleaseOKCode is the HTTP code returned for type PostConfigHalfcloseReleaseOK
const PostConfigHalfcloseReleaseOKCode int = 200

/*
PostConfigHalfcloseReleaseOK OK

swagger:response postConfigHalfcloseReleaseOK
*/
type PostConfigHalfcloseReleaseOK struct {

	/*
	  In: Body
	*/
	Payload *models.OperationResult `json:"body,omitempty"`
}

// NewPostConfigHalfcloseReleaseOK creates PostConfigHalfcloseReleaseOK with default headers values
func NewPostConfigHalfcloseReleaseOK() *PostConfigHalfcloseReleaseOK {

	return &PostConfigHalfcloseReleaseOK{}
}

// WithPayload adds the payload to the post config halfclose release o k response
func (o *PostConfigHalfcloseReleaseOK) WithPayload(payload *models.OperationResult) *PostConfigHalfcloseReleaseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose release o k response
func (o *PostConfigHalfcloseReleaseOK) SetPayload(payload *models.OperationResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseReleaseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseReleaseUnauthorizedCode is the HTTP code returned for type PostConfigHalfcloseReleaseUnauthorized
const PostConfigHalfcloseReleaseUnauthorizedCode int = 401

/*
PostConfigHalfcloseReleaseUnauthorized Invalid authentication credentials

swagger:response postConfigHalfcloseReleaseUnauthorized
*/
type PostConfigHalfcloseReleaseUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseReleaseUnauthorized creates PostConfigHalfcloseReleaseUnauthorized with default headers values
func NewPostConfigHalfcloseReleaseUnauthorized() *PostConfigHalfcloseReleaseUnauthorized {

	return &PostConfigHalfcloseReleaseUnauthorized{}
}

// WithPayload adds the payload to the post config halfclose release unauthorized response
func (o *PostConfigHalfcloseReleaseUnauthorized) WithPayload(payload *models.Error) *PostConfigHalfcloseReleaseUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose release unauthorized response
func (o *PostConfigHalfcloseReleaseUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseReleaseUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseReleaseForbiddenCode is the HTTP code returned for type PostConfigHalfcloseReleaseForbidden
const PostConfigHalfcloseReleaseForbiddenCode int = 403

/*
PostConfigHalfcloseReleaseForbidden Authenticated principal is not authorized for this operation

swagger:response postConfigHalfcloseReleaseForbidden
*/
type PostConfigHalfcloseReleaseForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseReleaseForbidden creates PostConfigHalfcloseReleaseForbidden with default headers values
func NewPostConfigHalfcloseReleaseForbidden() *PostConfigHalfcloseReleaseForbidden {

	return &PostConfigHalfcloseReleaseForbidden{}
}

// WithPayload adds the payload to the post config halfclose release forbidden response
func (o *PostConfigHalfcloseReleaseForbidden) WithPayload(payload *models.Error) *PostConfigHalfcloseReleaseForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose release forbidden response
func (o *PostConfigHalfcloseReleaseForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseReleaseForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseReleaseInternalServerErrorCode is the HTTP code returned for type PostConfigHalfcloseReleaseInternalServerError
const PostConfigHalfcloseReleaseInternalServerErrorCode int = 500

/*
PostConfigHalfcloseReleaseInternalServerError Internal service error

swagger:response postConfigHalfcloseReleaseInternalServerError
*/
type PostConfigHalfcloseReleaseInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseReleaseInternalServerError creates PostConfigHalfcloseReleaseInternalServerError with default headers values
func NewPostConfigHalfcloseReleaseInternalServerError() *PostConfigHalfcloseReleaseInternalServerError {

	return &PostConfigHalfcloseReleaseInternalServerError{}
}

// WithPayload adds the payload to the post config halfclose release internal server error response
func (o *PostConfigHalfcloseReleaseInternalServerError) WithPayload(payload *models.Error) *PostConfigHalfcloseReleaseInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose release internal server error response
func (o *PostConfigHalfcloseReleaseInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseReleaseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseReleaseServiceUnavailableCode is the HTTP code returned for type PostConfigHalfcloseReleaseServiceUnavailable
const PostConfigHalfcloseReleaseServiceUnavailableCode int = 503

/*
PostConfigHalfcloseReleaseServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response postConfigHalfcloseReleaseServiceUnavailable
*/
type PostConfigHalfcloseReleaseServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseReleaseServiceUnavailable creates PostConfigHalfcloseReleaseServiceUnavailable with default headers values
func NewPostConfigHalfcloseReleaseServiceUnavailable() *PostConfigHalfcloseReleaseServiceUnavailable {

	return &PostConfigHalfcloseReleaseServiceUnavailable{}
}

// WithPayload adds the payload to the post config halfclose release service unavailable response
func (o *PostConfigHalfcloseReleaseServiceUnavailable) WithPayload(payload *models.Error) *PostConfigHalfcloseReleaseServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose release service unavailable response
func (o *PostConfigHalfcloseReleaseServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseReleaseServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
