// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/loxilb-io/loxilb/api/models"
)

// PostConfigHalfcloseOKCode is the HTTP code returned for type PostConfigHalfcloseOK
const PostConfigHalfcloseOKCode int = 200

/*
PostConfigHalfcloseOK OK

swagger:response postConfigHalfcloseOK
*/
type PostConfigHalfcloseOK struct {

	/*
	  In: Body
	*/
	Payload *models.OperationResult `json:"body,omitempty"`
}

// NewPostConfigHalfcloseOK creates PostConfigHalfcloseOK with default headers values
func NewPostConfigHalfcloseOK() *PostConfigHalfcloseOK {

	return &PostConfigHalfcloseOK{}
}

// WithPayload adds the payload to the post config halfclose o k response
func (o *PostConfigHalfcloseOK) WithPayload(payload *models.OperationResult) *PostConfigHalfcloseOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose o k response
func (o *PostConfigHalfcloseOK) SetPayload(payload *models.OperationResult) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseBadRequestCode is the HTTP code returned for type PostConfigHalfcloseBadRequest
const PostConfigHalfcloseBadRequestCode int = 400

/*
PostConfigHalfcloseBadRequest Malformed arguments for API call

swagger:response postConfigHalfcloseBadRequest
*/
type PostConfigHalfcloseBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseBadRequest creates PostConfigHalfcloseBadRequest with default headers values
func NewPostConfigHalfcloseBadRequest() *PostConfigHalfcloseBadRequest {

	return &PostConfigHalfcloseBadRequest{}
}

// WithPayload adds the payload to the post config halfclose bad request response
func (o *PostConfigHalfcloseBadRequest) WithPayload(payload *models.Error) *PostConfigHalfcloseBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose bad request response
func (o *PostConfigHalfcloseBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseUnauthorizedCode is the HTTP code returned for type PostConfigHalfcloseUnauthorized
const PostConfigHalfcloseUnauthorizedCode int = 401

/*
PostConfigHalfcloseUnauthorized Invalid authentication credentials

swagger:response postConfigHalfcloseUnauthorized
*/
type PostConfigHalfcloseUnauthorized struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseUnauthorized creates PostConfigHalfcloseUnauthorized with default headers values
func NewPostConfigHalfcloseUnauthorized() *PostConfigHalfcloseUnauthorized {

	return &PostConfigHalfcloseUnauthorized{}
}

// WithPayload adds the payload to the post config halfclose unauthorized response
func (o *PostConfigHalfcloseUnauthorized) WithPayload(payload *models.Error) *PostConfigHalfcloseUnauthorized {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose unauthorized response
func (o *PostConfigHalfcloseUnauthorized) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(401)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseForbiddenCode is the HTTP code returned for type PostConfigHalfcloseForbidden
const PostConfigHalfcloseForbiddenCode int = 403

/*
PostConfigHalfcloseForbidden Authenticated principal is not authorized for this operation

swagger:response postConfigHalfcloseForbidden
*/
type PostConfigHalfcloseForbidden struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseForbidden creates PostConfigHalfcloseForbidden with default headers values
func NewPostConfigHalfcloseForbidden() *PostConfigHalfcloseForbidden {

	return &PostConfigHalfcloseForbidden{}
}

// WithPayload adds the payload to the post config halfclose forbidden response
func (o *PostConfigHalfcloseForbidden) WithPayload(payload *models.Error) *PostConfigHalfcloseForbidden {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose forbidden response
func (o *PostConfigHalfcloseForbidden) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseForbidden) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(403)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseInternalServerErrorCode is the HTTP code returned for type PostConfigHalfcloseInternalServerError
const PostConfigHalfcloseInternalServerErrorCode int = 500

/*
PostConfigHalfcloseInternalServerError Internal service error

swagger:response postConfigHalfcloseInternalServerError
*/
type PostConfigHalfcloseInternalServerError struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseInternalServerError creates PostConfigHalfcloseInternalServerError with default headers values
func NewPostConfigHalfcloseInternalServerError() *PostConfigHalfcloseInternalServerError {

	return &PostConfigHalfcloseInternalServerError{}
}

// WithPayload adds the payload to the post config halfclose internal server error response
func (o *PostConfigHalfcloseInternalServerError) WithPayload(payload *models.Error) *PostConfigHalfcloseInternalServerError {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose internal server error response
func (o *PostConfigHalfcloseInternalServerError) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseInternalServerError) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(500)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// PostConfigHalfcloseServiceUnavailableCode is the HTTP code returned for type PostConfigHalfcloseServiceUnavailable
const PostConfigHalfcloseServiceUnavailableCode int = 503

/*
PostConfigHalfcloseServiceUnavailable Management credential store unavailable; the credential could not be evaluated

swagger:response postConfigHalfcloseServiceUnavailable
*/
type PostConfigHalfcloseServiceUnavailable struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewPostConfigHalfcloseServiceUnavailable creates PostConfigHalfcloseServiceUnavailable with default headers values
func NewPostConfigHalfcloseServiceUnavailable() *PostConfigHalfcloseServiceUnavailable {

	return &PostConfigHalfcloseServiceUnavailable{}
}

// WithPayload adds the payload to the post config halfclose service unavailable response
func (o *PostConfigHalfcloseServiceUnavailable) WithPayload(payload *models.Error) *PostConfigHalfcloseServiceUnavailable {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post config halfclose service unavailable response
func (o *PostConfigHalfcloseServiceUnavailable) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostConfigHalfcloseServiceUnavailable) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(503)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
