// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// PostConfigHalfcloseHandlerFunc turns a function with the right signature into a post config halfclose handler
type PostConfigHalfcloseHandlerFunc func(PostConfigHalfcloseParams, interface{}) middleware.Responder

// Handle executing the request and returning a response
func (fn PostConfigHalfcloseHandlerFunc) Handle(params PostConfigHalfcloseParams, principal interface{}) middleware.Responder {
	return fn(params, principal)
}

// PostConfigHalfcloseHandler interface for that can handle valid post config halfclose params
type PostConfigHalfcloseHandler interface {
	Handle(PostConfigHalfcloseParams, interface{}) middleware.Responder
}

// NewPostConfigHalfclose creates a new http.Handler for the post config halfclose operation
func NewPostConfigHalfclose(ctx *middleware.Context, handler PostConfigHalfcloseHandler) *PostConfigHalfclose {
	return &PostConfigHalfclose{Context: ctx, Handler: handler}
}

/*
	PostConfigHalfclose swagger:route POST /config/halfclose postConfigHalfclose

# Set the half-close hold settings

Sets whether new holds may be taken and the idle bound on a hold. A field omitted keeps the value in force; a body with neither, or with a field the model does not have, is refused (400). The answer is the settings in force once applied. Blocking stops new holds only: the clients already held stay held until their answers are out or the bound ends them, and /config/halfclose/release is what closes them at once. A new bound applies to every hold from the next pass of the data path, those already held included. The settings are kept across a restart and in a configuration snapshot.
*/
type PostConfigHalfclose struct {
	Context *middleware.Context
	Handler PostConfigHalfcloseHandler
}

func (o *PostConfigHalfclose) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewPostConfigHalfcloseParams()
	uprinc, aCtx, err := o.Context.Authorize(r, route)
	if err != nil {
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}
	if aCtx != nil {
		*r = *aCtx
	}
	var principal interface{}
	if uprinc != nil {
		principal = uprinc.(interface{}) // this is really a interface{}, I promise
	}

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params, principal) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
