// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuditPolicy The runtime-changeable audit policy. A zero means "no limit" for every field except max_prune_per_pass, where it means the built-in default.
//
// swagger:model AuditPolicy
type AuditPolicy struct {

	// Seal the active segment once it has been open this long. Zero never seals by age, which leaves the unsealed part of the trail growing without bound and is what a profile ceiling refuses.
	MaxSegmentAgeSeconds int64 `json:"max_segment_age_seconds,omitempty"`

	// Seal the active segment before it exceeds this many bytes. Zero never seals by size.
	MaxSegmentBytes int64 `json:"max_segment_bytes,omitempty"`

	// Prune a sealed segment older than this. Zero keeps by age forever, which is the strongest setting and never below a floor.
	RetentionMaxAgeSeconds int64 `json:"retention_max_age_seconds,omitempty"`

	// Prune oldest first while the sealed segments exceed this total. Zero disables the quota. A quota below one segment is refused, since pruning could never satisfy it.
	RetentionMaxBytes int64 `json:"retention_max_bytes,omitempty"`

	// Deletions allowed per retention pass. Zero means the built-in default of one.
	RetentionMaxPrunePerPass int64 `json:"retention_max_prune_per_pass,omitempty"`

	// Free-space floor on the audit filesystem. Below it, pruning proceeds regardless of age and quota and durable management writes are refused. Zero disables the check.
	RetentionReserveBytes int64 `json:"retention_reserve_bytes,omitempty"`
}

// Validate validates this audit policy
func (m *AuditPolicy) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this audit policy based on context it is used
func (m *AuditPolicy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuditPolicy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuditPolicy) UnmarshalBinary(b []byte) error {
	var res AuditPolicy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
