// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuditSink The remote sink's configuration and session state. Certificate material is named by path and never served.
//
// swagger:model AuditSink
type AuditSink struct {

	// The receiver's host and port.
	Address string `json:"address,omitempty"`

	// PEM bundle the receiver's certificate is verified against. Required; there is no unverified mode.
	CaBundlePath string `json:"ca_bundle_path,omitempty"`

	// Client certificate for mutual TLS. Both this and the key must be set, or neither.
	ClientCertPath string `json:"client_cert_path,omitempty"`

	// Client key for mutual TLS.
	ClientKeyPath string `json:"client_key_path,omitempty"`

	// Read-only. Whether a session is currently established.
	Connected bool `json:"connected,omitempty"`

	// Whether a sink is configured and submitting.
	Enabled bool `json:"enabled,omitempty"`

	// Syslog facility. Defaults to 13, log audit.
	Facility int64 `json:"facility,omitempty"`

	// Read-only. The most recent transport error, empty when the last attempt succeeded.
	LastError string `json:"last_error,omitempty"`

	// Largest message this receiver accepts. A record that does not fit is truncated at a field boundary and marked, never cut mid-record. Zero means no limit.
	MaxFrameBytes int64 `json:"max_frame_bytes,omitempty"`

	// Name expected in the receiver's certificate. Defaults to the host part of the address.
	ServerName string `json:"server_name,omitempty"`

	// Read-only. Records written to the socket since this sink was configured. Not a delivery count, the protocol carries no acknowledgement.
	Submitted int64 `json:"submitted,omitempty"`

	// Read-only. Records that did not fit the receiver's cap and were sent shortened.
	Truncated int64 `json:"truncated,omitempty"`

	// Read-only. Submissions that failed, each of which stops the cursor from advancing.
	WriteErrors int64 `json:"write_errors,omitempty"`
}

// Validate validates this audit sink
func (m *AuditSink) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this audit sink based on context it is used
func (m *AuditSink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuditSink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuditSink) UnmarshalBinary(b []byte) error {
	var res AuditSink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
