// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuditSinkFilter What a secondary sink selects from the trail. Each field that is set narrows the selection, and a field judges only the records that have what it looks at.
//
// swagger:model AuditSinkFilter
type AuditSinkFilter struct {

	// Keep one data record in this many. Zero and one keep all. Only the data stream can be sampled.
	DataSample int64 `json:"data_sample,omitempty"`

	// Keep records whose outcome is ok, or failed. Empty keeps both.
	Outcome string `json:"outcome,omitempty"`

	// Keep data records of these services. Records of other streams are not judged by it.
	Services []string `json:"services"`

	// Keep records of these streams (mgmt, data, audit_system). Empty keeps all.
	Streams []string `json:"streams"`
}

// Validate validates this audit sink filter
func (m *AuditSinkFilter) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this audit sink filter based on context it is used
func (m *AuditSinkFilter) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuditSinkFilter) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuditSinkFilter) UnmarshalBinary(b []byte) error {
	var res AuditSinkFilter
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
