// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuditSinkCursor A place in the trail, the last record a sink is past.
//
// swagger:model AuditSinkCursor
type AuditSinkCursor struct {

	// The segment the record is in.
	SegmentUUID string `json:"segment_uuid,omitempty"`

	// The record's sequence number.
	Seq int64 `json:"seq,omitempty"`
}

// Validate validates this audit sink cursor
func (m *AuditSinkCursor) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this audit sink cursor based on context it is used
func (m *AuditSinkCursor) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *AuditSinkCursor) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuditSinkCursor) UnmarshalBinary(b []byte) error {
	var res AuditSinkCursor
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
