// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuditSinkStatus One sink's progress through the trail.
//
// swagger:model AuditSinkStatus
type AuditSinkStatus struct {

	// The sink that receives every record.
	Compliance bool `json:"compliance,omitempty"`

	// cursor
	Cursor *AuditSinkCursor `json:"cursor,omitempty"`

	// The sink has reached the segment being written. When false it is still reading sealed segments and lag_records does not apply.
	InActiveSegment bool `json:"in_active_segment,omitempty"`

	// Times a segment was removed by retention before this sink had read it out.
	LagDrops int64 `json:"lag_drops,omitempty"`

	// Records written to the active segment that the sink is not yet past. Zero while the sink is still in a sealed segment.
	LagRecords int64 `json:"lag_records,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// starting, connected, disconnected, stalled or stopped. connected says the last record offered was written to a session the receiver has not closed. It does not say the receiver has stored it: a receiver that stops answering without closing is found only when the transport gives up on it, some seconds later.
	State string `json:"state,omitempty"`
}

// Validate validates this audit sink status
func (m *AuditSinkStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCursor(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuditSinkStatus) validateCursor(formats strfmt.Registry) error {
	if swag.IsZero(m.Cursor) { // not required
		return nil
	}

	if m.Cursor != nil {
		if err := m.Cursor.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cursor")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cursor")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this audit sink status based on the context it is used
func (m *AuditSinkStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCursor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuditSinkStatus) contextValidateCursor(ctx context.Context, formats strfmt.Registry) error {

	if m.Cursor != nil {
		if err := m.Cursor.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cursor")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cursor")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuditSinkStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuditSinkStatus) UnmarshalBinary(b []byte) error {
	var res AuditSinkStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
