// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// AuditNamedSink A secondary sink's configuration and state. Certificate material is named by path and never served.
//
// swagger:model AuditNamedSink
type AuditNamedSink struct {

	// The receiver's host and port.
	Address string `json:"address,omitempty"`

	// PEM bundle the receiver's certificate is verified against. Required; there is no unverified mode.
	CaBundlePath string `json:"ca_bundle_path,omitempty"`

	// Client certificate for mutual TLS. Both this and the key must be set, or neither.
	ClientCertPath string `json:"client_cert_path,omitempty"`

	// Client key for mutual TLS.
	ClientKeyPath string `json:"client_key_path,omitempty"`

	// cursor
	Cursor *AuditSinkCursor `json:"cursor,omitempty"`

	// The IANA private enterprise number that qualifies the export sequence element. Required; none is built in.
	EnterpriseNumber int64 `json:"enterprise_number,omitempty"`

	// Syslog facility. Defaults to 13, log audit.
	Facility int64 `json:"facility,omitempty"`

	// filter
	Filter *AuditSinkFilter `json:"filter,omitempty"`

	// Read-only. Records the filter kept from this sink.
	Filtered int64 `json:"filtered,omitempty"`

	// Read-only. Times a segment was removed by retention before this sink had read it out.
	LagDrops int64 `json:"lag_drops,omitempty"`

	// Read-only. The most recent error, empty when the last attempt succeeded.
	LastError string `json:"last_error,omitempty"`

	// Largest message this receiver accepts. Zero means no limit.
	MaxFrameBytes int64 `json:"max_frame_bytes,omitempty"`

	// Read-only. The sink's name, from the path.
	Name string `json:"name,omitempty"`

	// Read-only. Records skipped because the sink cannot carry them.
	Poison int64 `json:"poison,omitempty"`

	// Read-only. Submissions that repeated an earlier one after a session failed.
	Resent int64 `json:"resent,omitempty"`

	// Name expected in the receiver's certificate. Defaults to the host part of the address.
	ServerName string `json:"server_name,omitempty"`

	// Read-only. starting, connected, disconnected, stalled or stopped.
	State string `json:"state,omitempty"`

	// Read-only. Records written to the socket since this sink was configured, records sent again included. Not a delivery count.
	Submitted int64 `json:"submitted,omitempty"`

	// Read-only. Records that did not fit the receiver's cap and were sent shortened.
	Truncated int64 `json:"truncated,omitempty"`

	// Read-only. Submissions that failed, each of which stops the cursor from advancing.
	WriteErrors int64 `json:"write_errors,omitempty"`

	// Read-only. The epoch of the export sequence. It changes whenever the count starts again.
	XseqEpoch int64 `json:"xseq_epoch,omitempty"`

	// Read-only. The highest export sequence number the sink has used.
	XseqHigh int64 `json:"xseq_high,omitempty"`
}

// Validate validates this audit named sink
func (m *AuditNamedSink) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCursor(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateFilter(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuditNamedSink) validateCursor(formats strfmt.Registry) error {
	if swag.IsZero(m.Cursor) { // not required
		return nil
	}

	if m.Cursor != nil {
		if err := m.Cursor.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cursor")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cursor")
			}
			return err
		}
	}

	return nil
}

func (m *AuditNamedSink) validateFilter(formats strfmt.Registry) error {
	if swag.IsZero(m.Filter) { // not required
		return nil
	}

	if m.Filter != nil {
		if err := m.Filter.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filter")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filter")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this audit named sink based on the context it is used
func (m *AuditNamedSink) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCursor(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateFilter(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *AuditNamedSink) contextValidateCursor(ctx context.Context, formats strfmt.Registry) error {

	if m.Cursor != nil {
		if err := m.Cursor.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cursor")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("cursor")
			}
			return err
		}
	}

	return nil
}

func (m *AuditNamedSink) contextValidateFilter(ctx context.Context, formats strfmt.Registry) error {

	if m.Filter != nil {
		if err := m.Filter.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("filter")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("filter")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *AuditNamedSink) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *AuditNamedSink) UnmarshalBinary(b []byte) error {
	var res AuditNamedSink
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
