// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// CertCreated The handle of a certificate that was created.
//
// swagger:model CertCreated
type CertCreated struct {

	// The ID the certificate is stored under - the one the request named, or the one the server minted when it named none. It is the handle for rotate and delete, and what a load-balancer rule refers to.
	// Required: true
	CertID *string `json:"certId"`
}

// Validate validates this cert created
func (m *CertCreated) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCertID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *CertCreated) validateCertID(formats strfmt.Registry) error {

	if err := validate.Required("certId", "body", m.CertID); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this cert created based on context it is used
func (m *CertCreated) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *CertCreated) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *CertCreated) UnmarshalBinary(b []byte) error {
	var res CertCreated
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
