// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// Cert Managed PEM input and partial read model. POST currently returns empty 201, including when it mints an ID; callers cannot obtain that minted handle from the response. PUT uses the path ID and ignores body ID and hostnames. Known lifecycle gaps: duplicate POST persists before rejecting registration and can remove existing material; failed rotation does not roll back files; hostname ownership conflicts and multi-host swaps are not transactional; rotation retains the old hostname set. Do not claim atomic certificate transactions, automatic SAN migration, or verified zero downtime. GET returns no private-key material, although the shared schema still requires keyPem and the generated response can serialize it as null.
//
// swagger:model Cert
type Cert struct {

	// Opaque handle, client-supplied or minted when absent/empty on POST. PUT uses the path handle. Current validation permits at most 63 bytes and rejects path separators and any '..' substring; NUL validation is incomplete. Minted handles are currently not returned by POST.
	CertID *string `json:"certId,omitempty"`

	// Leaf certificate PEM required on POST/PUT. The Go handler checks PEM armor; authoritative X.509/key parsing occurs in the OpenSSL loader after persistence. A 400 load failure does not imply transactional rollback of persisted material.
	// Required: true
	CertPem *string `json:"certPem"`

	// Optional intermediate-chain PEM appended after the leaf.
	ChainPem string `json:"chainPem,omitempty"`

	// Output-only. SAN-DNS/CN auto-derived hostnames the certId registered into the SNI store. Ignored on POST/PUT.
	Hostnames []string `json:"hostnames"`

	// Private key in PEM on POST/PUT for usage "server" and "client". For usage "ca" the member is still sent and must be the empty string; a key is refused. Persisted 0600 (key-at-rest). Never returned on GET.
	// Required: true
	KeyPem *string `json:"keyPem"`

	// What the entry is for, fixed when the ID is created. "server": a listener certificate and key, selected by SNI. "ca": a bundle of CA certificates that backend certificates are verified against; certPem (plus chainPem) is the bundle and keyPem is the empty string. "client": the certificate and key the gateway presents to backends. Only "server" entries are offered to clients. A load-balancer rule refers to a "ca" entry with backend_ca_cert_id and to a "client" entry with backend_client_cert_id; an entry a rule refers to cannot be deleted. A rotated "ca" or "client" entry takes effect on a rule when that rule is next updated.
	// Enum: [server ca client]
	Usage *string `json:"usage,omitempty"`
}

// Validate validates this cert
func (m *Cert) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCertPem(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKeyPem(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUsage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *Cert) validateCertPem(formats strfmt.Registry) error {

	if err := validate.Required("certPem", "body", m.CertPem); err != nil {
		return err
	}

	return nil
}

func (m *Cert) validateKeyPem(formats strfmt.Registry) error {

	if err := validate.Required("keyPem", "body", m.KeyPem); err != nil {
		return err
	}

	return nil
}

var certTypeUsagePropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["server","ca","client"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		certTypeUsagePropEnum = append(certTypeUsagePropEnum, v)
	}
}

const (

	// CertUsageServer captures enum value "server"
	CertUsageServer string = "server"

	// CertUsageCa captures enum value "ca"
	CertUsageCa string = "ca"

	// CertUsageClient captures enum value "client"
	CertUsageClient string = "client"
)

// prop value enum
func (m *Cert) validateUsageEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, certTypeUsagePropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *Cert) validateUsage(formats strfmt.Registry) error {
	if swag.IsZero(m.Usage) { // not required
		return nil
	}

	// value enum
	if err := m.validateUsageEnum("usage", "body", *m.Usage); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this cert based on context it is used
func (m *Cert) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *Cert) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *Cert) UnmarshalBinary(b []byte) error {
	var res Cert
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
