// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HalfCloseConfig The process-wide half-close hold settings. They apply to the services that hold: those whose half_close_mode is hold, and those that leave it unset while defaultMode is hold. A field this model does not have is refused (400), so a misspelt one cannot pass for a change that was not made.
//
// swagger:model HalfCloseConfig
type HalfCloseConfig struct {

	// Whether new holds may be taken. false blocks them on every service, whatever its mode, and leaves the clients already held to finish.
	Allow *bool `json:"allow,omitempty"`

	// The idle bound on a hold, in seconds: a held client to which no answer byte has been written for this long is closed. The clock starts once the request has reached the backend and restarts with every write of the answer, so a long answer that keeps coming is never cut by it.
	// Maximum: 3600
	// Minimum: 1
	CapSeconds *int32 `json:"capSeconds,omitempty"`

	// The half-close mode of a service that leaves its own half_close_mode unset: off (the default) or hold. It reaches only the services that could take hold themselves - fullproxy, plaintext clients, not P/D; the others run off whatever it is, and a service's half_close_effective says which applies. A change applies at once to every service it reaches, for half-closes from then on: clients already held finish as they started. null, inherit (there is nothing to inherit from) and hold+parked (not available yet) are refused (400).
	DefaultMode *string `json:"defaultMode,omitempty"`
}

// Validate validates this half close config
func (m *HalfCloseConfig) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCapSeconds(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HalfCloseConfig) validateCapSeconds(formats strfmt.Registry) error {
	if swag.IsZero(m.CapSeconds) { // not required
		return nil
	}

	if err := validate.MinimumInt("capSeconds", "body", int64(*m.CapSeconds), 1, false); err != nil {
		return err
	}

	if err := validate.MaximumInt("capSeconds", "body", int64(*m.CapSeconds), 3600, false); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this half close config based on context it is used
func (m *HalfCloseConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *HalfCloseConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HalfCloseConfig) UnmarshalBinary(b []byte) error {
	var res HalfCloseConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
